### ISSUE TITLE
Hover popup is too small for hint text

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#102]
Hovering on expressions to examine their type is barely readable:

![selection_009](https://user-images.githubusercontent.com/889291/43368778-90853802-935a-11e8-977a-3dc8d50ce33d.png)

**Comment by norru** [comment]
Workaround: Preferences -> General -> Editors -> Text Editors -> (disable) "Show affordance in hover on how to make it sticky"

**Comment by mickaelistria** [comment]
It seems a bit like https://bugs.eclipse.org/bugs/show_bug.cgi?id=516960
Can you please detail how you installed corrosion? In Help > About Eclipse IDE > Installation Details > Plugins, can you please look at the version of org.eclipse.lsp4e?

**Comment by norru** [comment]
It does appear to be the same bug.

**Comment by norru** [comment]
I have updated lsp4e to ```0.7.0.201807181421``` and the problem persists.

**Comment by LucasBullen** [comment]
[New patch to lsp4e](http://git.eclipse.org/c/lsp4e/lsp4e.git/commit/?id=beadb67d153f81e2f644e17a9af68cf64a549c71) will fix this issue adding a buffer below the hover result to offset the `Press 'F2' for focus` line.

Until this new version of lsp4e is in use, use the workaround found above (https://github.com/eclipse/corrosion/issues/102#issuecomment-408704206)
