### ISSUE TITLE
Implement comment/uncomment region

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#105]
In many other plugins/IDEs it is possible to comment/uncomment a block by selecting the block and hitting {{Ctrl+Shift+/}} or a similar keychord.

This doesn't seem to be implemented in the current editor. If it is, I've missed it! What's the mapping?

**Comment by LucasBullen** [comment]
On the queue of features that will be implemented in TM4E once language-configuration.json files are fully supported. https://github.com/eclipse/tm4e/issues/159

**Comment by LucasBullen** [comment]
This has now been implemented in TM4E and inherited in f32d634.
View the `TextMate > Language Configurations` for all the new features added with this patch

View the `General > Keys` preference page for the **TM4E Language Configuration** category of commands to see/edit the comment/uncomment command bindings as they are subject to change (https://github.com/eclipse/tm4e/issues/172)
