### ISSUE TITLE
Fix for Issue #99 breaks debugging

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#106]
Hi,

I have installed https://github.com/LucasBullen/corrosion/commit/f6282007ef747ff353da14b68c475e099d64119d from source.

This breaks debugging as the IDE can no longer resolve source files
![workspace_rust_clean - rust-oids-src-main rs - eclipse ide _011](https://user-images.githubusercontent.com/889291/43967507-719a3eea-9cbc-11e8-9b29-f75fac734d52.png)

**Comment by norru** [comment]
Reverting to the "official" fix at 10e7c319afd7496f507d4c2b16d3e16b7f091b6b solves the problem.

**Comment by LucasBullen** [comment]
Good find, #107 fixes this issue for my test cases, care to confirm/test the PR for your case before I merge it?

**Comment by norru** [comment]
Jumping on it :)

**Comment by norru** [comment]
Yep, seems to work!
