### ISSUE TITLE
Continue doc-comment on new line

### ISSUE THREAD

**Issue by Boereck** [eclipse/corrosion#109]
Hi,

Often when writing doc comments (lines starting with `///` or `//!` ) it would be nice if, when hitting enter, the next line would start with the same doc comment sequence. This is implemented in VSCode as well and I miss this feature every time when editing with Corrosion.

I wonder how difficult it is to teach the generic editor this trick for Rust code.

**Comment by mickaelistria** [comment]
I think it's be more interesting to try to tweak it for any editor using a language-configuration.json (in tm4e).

**Comment by Boereck** [comment]
Is it possible to define multiple `lineComment`s in language-configuration.json? Because if (in case of Rust) this feature would only duplicate the "standard" single line comment `//` this would not be that helpful. An extension to the JSON format would be possible, of course. The question then would be if this should be proposed as a change to VSCode as well. I guess the rls-vscode plugin authors would be glad as well if this feature could be solved generically and in a declarative fashion via the language-configuration.json file.

**Comment by LucasBullen** [comment]
This will be done with [TM4E](https://github.com/eclipse/tm4e). We are in the process of adding the remaining language-configuration features, then [on enter actions that you use in vscode](https://github.com/rust-lang-nursery/rls-vscode/blob/f2752fe6db1219c162368c192b4ec705a97c3735/src/extension.ts#L444) will be present, including the one you've described. So hold on tight or come help with contributions to [the related issue in TM4E](https://github.com/eclipse/tm4e/issues/168)! :+1:

**Comment by LucasBullen** [comment]
This has now been implemented in TM4E and inherited in f32d634 with the addition of on enter rules.
View the `TextMate > Language Configurations` for all the new features added with this patch.

Typing `///` or `//!` then pressing enter will add the same line comment to the new line

Typing `/**` or having a line starting with ` * ` will add ` * ` to the next line

**Comment by Boereck** [comment]
Thanks guys, you are wicked fast! I have some remarks: The doc comments `///` and `//!` work as expected. This is exactly what I needed. The block comments behave weird though. Some of these issues may be problems with the generic implementation, since the onEnterRules seem to be the same as for VS Code, but behave differently. 
* If you type `/**` it will be completed, but the cursor is set to the "wrong" position `*<curser_pos>/`. Same for the outer doc comment `/*!`.  
* When inside the block comment pressing enter, the indentation is removed and the next line starting from the beginning. In VS Code the next `*` starts right below of the first star in the leading `/**`. 
* When being in a doc comment that is opened and closed in one line (like this: `/** <curser_pos>*/`) pressing enter, the indentation of the closing `*/` is off as well. 
* It seems as a follow up error from the error above, pressing enter again will not produce a line starting with `* `. When manually indent the empty block comment line, the next line will start with a star again.

I don't know if the implementation of onEnterRules are currently (deliberately) incomplete or buggy. 
Block doc-comments are extremely rare in Rust (line doc-comments are considered idiomatic), but I guess this should be fixed anyway 😉

**Comment by LucasBullen** [comment]
Rust uses spaces instead of tabs and parts of the functionality are based around this being set as the default.

In the preferences either go `Rust > Text Editor > **See Text Editors**` or `General > Editors > Text Editors` (Both different paths to the same page) and turn on the top most check box enabling **Insert spaces for tabs**. You may have to reopen any active editors for the changes to take place.

Doing this will insert X spaces when pressing tab and will fix most of the block comment issues, do say if any issues still persist after doing this or if you have a reason why you would not wish to set the default to spaces.

Hope this helps!

**Comment by Boereck** [comment]
Hey Lucas, thanks this gets rid of most of the problems! Maybe the generic editor should allow a language specific version for the tabs vs. spaces setting overwriting the general `Text Editors` settings.

The cursor is still placed weird on auto-close of doc-comment (see last comment).
