### ISSUE TITLE
Raw string coloring buggy

### ISSUE THREAD

**Issue by Boereck** [eclipse/corrosion#115]
Hi, the way how the syntax coloring of raw strings work is not correct. If you look at the [reference](https://doc.rust-lang.org/reference/tokens.html#characters-and-strings) you will see that there is a flexible amount of # delimiters that can be used. E.g. `let foo = r##" "# "##;` is a valid raw string. To correct the current Textmate grammar, you can replace the current `rust_raw_string` rule with this one:
```xml
<key>rust_raw_string</key>
<dict>
    <key>begin</key>
    <string>r(#*)"</string>
    <key>end</key>
    <string>"(\1)</string>
    <key>name</key>
    <string>string.quoted.other.raw.rust</string>
</dict>
```
It seems the rule also has to be move above the `rust_string` rule to have higher precedence. I don't know where you got the grammar from and if you want yours to diverge from the original. If not this issue maybe should be opened for the originating project.
EDIT: The `rust_raw_string` rule already is above `rust_string`, I guess I played around too much with the grammar, before landing on a version that worked.

**Comment by LucasBullen** [comment]
We got the language from https://github.com/defuz/sublimate/packages/Rust/Rust.tmLanguage, however it has not been active for 3 years. It would be fine if we make these changes here. Would you be interested in making the PR? See [the contributing document](https://github.com/eclipse/corrosion/blob/master/CONTRIBUTING.md) for instruction on how. Any questions on the process ask away! :)

**Comment by mickaelistria** [comment]
Or maybe there is a better TextMate grammar we can pick somewhere else?
If one grammar acts as a reference, then it's better to fix the grammar and fetch it in Corrosion than to let Corrosion fork this reference grammar. How does this behave in other IDEs?
For sure, a better grammar would be a competitive advantage, but it's also important to think about improving the world at large, even if this involved making fixes other IDEs/editors will benefit from ;)

**Comment by Boereck** [comment]
Sure I could start a PR, for now. 
I know in VS Code the grammar seems to do the right thing with regard to raw strings. I think they have their grammar from another Repo as well. I can investigate where their grammar is originally from. If this grammar has more recent updates this could be a better overall alternative. I'll let you know.

**Comment by Boereck** [comment]
Alright, so the grammar from VS Code is located here: 
https://github.com/Microsoft/vscode/blob/master/extensions/rust/syntaxes/rust.tmLanguage.json
This grammar itself is coming from this grammar:
https://github.com/zargony/atom-language-rust/blob/master/grammars/rust.cson
VS Codes version seems to be updated regularly when the original updates. The updates to the grammar are more recent and seem to do a solid job.

Both versions are MIT licensed. VS Code's version can be transformed into an XML version using a VS Code plugin.

**Comment by mickaelistria** [comment]
>
> This grammar itself is coming from this grammar:
> https://github.com/zargony/atom-language-rust/blob/
> master/grammars/rust.cson
>

Should we use directly this one?


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by Boereck** [comment]
Well, I don't know enough about cson file format. I guess we would have to transform CSON to JSON to get it working with TM4E, right? But if we get this done, I think the "original" from the `atom-language-rust` repo would be the better choice. From what I have read in issues, the VS Code team does not want to update the grammar themselves, but refer to the original repo for improvements.

**Comment by mickaelistria** [comment]
Ok thanks.
TM4E can't read cson filesand it might be the same for vscode hence why
they translate changes in.cson into their json file.
The most profitable flow seems to be consuming the file from vscode then.


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by Boereck** [comment]
Yeah, taking VS Code's version would be the path of least resistance, allowing friction-less updates in the future. I also think they adopt changes to the original in a timely fashion.

**Comment by mickaelistria** [comment]
@Boereck Ok. Can you please prepare the PR? I'll take care of declaring the reuse to the Eclipse IP procedure.

**Comment by Boereck** [comment]
Yep, I can prepare a PR this evening.

**Comment by mickaelistria** [comment]
This is expected to be fixed by https://github.com/eclipse/corrosion/commit/ebedbb50a752ee72e218fd4f9d471a8fc8b3d20f . Please reopen if it's still happening with latest snapshots.
