### ISSUE TITLE
Unable to import exisitng cargo projects

### ISSUE THREAD

**Issue by 0xpr03** [eclipse/corrosion#119]
Currently you can't tell corrosion to create a new project based on an existing, pure cargo project. (No Eclipse project before), like a "Import existing Rust project".
AFAIK you have to create a new project and copy over the existing sourcecode as of now.
This makes it pretty annoying to use corrosion on pre-corrosion projects.

**Comment by mickaelistria** [comment]
Have you tried File > Import projects from Filesystem... ?
As there is no need for a specific import wizard (the Rust project are not specific projects), the default wizard should work.

In any case, I think it's a dup of #92 which was fixed in July with https://github.com/eclipse/corrosion/commit/ec6badb8432b8478a4580c261fcb356b91c3a565 . You may try a snapshot build to see this explained better in the UI.
Closing.

**Comment by 0xpr03** [comment]
I think you misunderstood me.
First of all there is only File -> Import... -> General -> File System.
Second that does fail as it wants to import this into some folder.
I want to use my bar metal rust program in eclipse, a program which hasn't used in eclipse at all.

**Comment by mickaelistria** [comment]
> I think you misunderstood me.

I don't think so ;)

> First of all there is only File -> Import... -> General -> File System.

Then it's a bug in Eclipse IDE. There is https://www.eclipse.org/eclipse/news/4.6/M7/#Import-projects which adds a menu entry `File > Open projects from filesystem...` which you should use. It's also available at `File > Import... > General > Projects from Filesystem or Archive`. This will just open your code in the Eclipse IDE, without duplicating it, and if it's a Rust project with a cargo descriptor file, then it will be identified as such and the contextual actions will be available.

The `File > Import... > Generat > Filesystem` will tend to copy the content to some other project. It's not what you want.

**Comment by 0xpr03** [comment]
> which adds a menu entry File > Open projects from filesystem... which you should

ah, now I've found the correct entry
I'd recommend to document this behaviour in the readme. "projects from filesystem" is is to me "use an existing eclipse project".
Sorry for taking your time.

> I don't think so ;)

Indeed

**Comment by mickaelistria** [comment]
> I'd recommend to document this behaviour in the readme. "projects from filesystem" is is to me "use an existing eclipse project".

A pull request on this topic would be welcome ;)

**Comment by 0xpr03** [comment]
I'll do one when I've the time to sign the CLA. Sad to say that currently the UI hangs on mouse hover (basically moving it) or file switches are making console+text editor way faster. I'm aware of the upstream bugs causing this.
