### ISSUE TITLE
language-configuration file for Rust does not load properly in TextMate settings

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#124]
- Preferences -> TextMate -> Language Configuration -> select the default language-configuration.json  - The settings appear blank:

![preferences _017](https://user-images.githubusercontent.com/889291/45258152-df7b1d80-b3aa-11e8-9673-b01ae937bdbe.png)

This is what happens when loading the same file (?) as custom configuration using the `New...` button:

![preferences _018](https://user-images.githubusercontent.com/889291/45258153-ea35b280-b3aa-11e8-9705-de47f249f417.png)

Unfortunately the default one appears to have a higher priority so the custom settings are also ignored.

Version: dev head, built from source:

```
Author: Lucas Bullen <lbullen@redhat.com>
Date:   Fri Aug 24 10:00:32 2018 -0400

    Replace images with gifs in README
    
    Signed-off-by: Lucas Bullen <lbullen@redhat.com>
```

**Comment by norru** [comment]
I found the root cause

The `language-configurations/language-configuration.json` file is missing in the plugin's jar.

**Comment by mickaelistria** [comment]
Thanks a lot @norru , good catch!
Would you like to provide a PR? It involves just adding the language-configurations folder to the bin.. entry of build.properties.

**Comment by norru** [comment]
Unfortunately I'm tied up - I barely have the time to make bug reports :)

If it helps, adding the file manually to the built jar actually fixes the problem.

**Comment by norru** [comment]
If nobody gets to do it earlier, I'll try to do it during the weekend. Which branch should I sync to, would `master` do?

**Comment by mickaelistria** [comment]
Fixed as a symptom for the same root cause in #131
