### ISSUE TITLE
Cargo.toml changes aren't picked up by RLS

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#126]
RLS does not seem to be aware of `Cargo.toml` or 'Cargo.lock` changes. I guess this is another of "the LSP client should tell the RLS to reload" issues.

As a workaround, is there a way of triggering a RLS restart without restarting the whole IDE?

**Comment by mickaelistria** [comment]
> As a workaround, is there a way of triggering a RLS restart without restarting the whole IDE?

Closing all editors using the Language Server should stop the language server.
Then opening an editor which uses the LS will restart it.

**Comment by norru** [comment]
Thanks for the tip, I'll try.

**Comment by norru** [comment]
Hi @mickaelistria, I've tried the workaround you suggested and the RLS doesn't seem to always terminate when I close all files. Sometimes it does but in general the only reliable way to work this around is to restart the IDE.

**Comment by norru** [comment]
@mickaelistria @nrc Was this fixed? I just made a change to Cargo and I didn't have to restart the IDE (as usually had to)

**Comment by mickaelistria** [comment]
Nothing was changed on that matter, but RLS may have magically fixed it.
What I can suggest is that you write an automated test to cover this story; and either it's green and we keep it to notice potential regressions; or it's red and we fix it and keep it to notice potential regressiosn.
