### ISSUE TITLE
Random hangs, cannot recover

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#128]
I am now using Corrosion in anger for some (non critical) production work.

I had it freezing on me twice, while editing Rust code. Waiting didn't solve the issue and each time I had to forcibly terminate the IDE.

I have no other clues, feel free to ask for more information.

**Comment by mickaelistria** [comment]
When this happen, please run `jstack <pid>` in the console and share the output on the ticket. We'll immediately see which piece of code is freezing the IDE.

**Comment by norru** [comment]
Just got another freeze:

[stack_on_stuck_ide.txt](https://github.com/eclipse/corrosion/files/2380378/stack_on_stuck_ide.txt)

**Comment by norru** [comment]
```
"main" #1 prio=6 os_prio=0 tid=0x0000000000f75000 nid=0x4a85 waiting for monitor entry [0x00007ffe47fc3000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.eclipse.ui.console.IOConsoleOutputStream.isClosed(IOConsoleOutputStream.java:159)
	- waiting to lock <0x000000048f2662f0> (a org.eclipse.ui.console.MessageConsoleStream)
	at org.eclipse.lsp4e.LoggingStreamConnectionProviderProxy.logToConsole(LoggingStreamConnectionProviderProxy.java:223)
	at org.eclipse.lsp4e.LoggingStreamConnectionProviderProxy.access$4(LoggingStreamConnectionProviderProxy.java:222)
	at org.eclipse.lsp4e.LoggingStreamConnectionProviderProxy$4.write(LoggingStreamConnectionProviderProxy.java:164)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:63)
```

If it helps, I do have the lsp logging on its console (to troubleshoot RLS problems).

**Comment by mickaelistria** [comment]
Ok, it seems indeed caused by the logging to console feature. It seems like a bug in LSP4E under certain conditions.
As a workaround, I can suggest you disable the log to console feature, and instead log to a file. Then open that file in the IDE with the text editor to manipulate it, or even with the internal web browser which has an auto-refresh strategy ( https://www.eclipse.org/eclipse/news/4.8/M4/#browser-autorefresh ).
HTH

**Comment by norru** [comment]
I can tail the file, provided I can find it.

Loading a file and refresh it in the editor is terrible if I'm only interested in what the server is doing in real time. In my last experience, the internal web browser is bloated and unreliable so I'd rather avoid.

**Comment by norru** [comment]
Found, it's in the root of the workspace.

```
norru@GBWWSRUNUBWS02:~/Workspaces/workspace_rust$ find . -name "languageServers-log"
./languageServers-log
```

**Comment by norru** [comment]
Opened lsp4e bug at https://bugs.eclipse.org/bugs/show_bug.cgi?id=539126

**Comment by norru** [comment]
Bug still "UNCONFIRMED"

**Comment by norru** [comment]
Here's a nice log viewer to replace the broken log to console: https://glogg.bonnefon.org/

**Comment by norru** [comment]
Moved to https://bugs.eclipse.org/bugs/show_bug.cgi?id=540852

**Comment by mickaelistria** [comment]
Was fixed upstream some time ago.
