### ISSUE TITLE
@Windows: Rust Language Server not found. Update in Rust preferences

### ISSUE THREAD

**Issue by anb0s** [eclipse/corrosion#130]
Using rust plugin:
  Corrosion: Rust edition in Eclipse IDE	0.1.0.201809121453	org.eclipse.corrosion.feature.feature.group	Red Hat Inc.

Exception if opening *.rs file:
Rust Language Server not found. Update in Rust preferences.

and java.lang.NullPointerException in Outline view

and
org.eclipse.lsp4e
Error
Thu Sep 13 21:04:53 CEST 2018
Input stream must be configured.

java.lang.IllegalStateException: Input stream must be configured.
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:263)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createIoLauncher(Launcher.java:118)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createLauncher(Launcher.java:94)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:210)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:520)
	at org.eclipse.lsp4e.LanguageServiceAccessor$LSPDocumentInfo.getInitializedLanguageClient(LanguageServiceAccessor.java:121)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.collectHighlights(HighlightReconcilingStrategy.java:152)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.lambda$1(HighlightReconcilingStrategy.java:124)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:182)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

**Comment by mickaelistria** [comment]
Did you try to.configure Rust Language Server in Preferences as recommended?

**Comment by norru** [comment]
Just two basic checks:

- are you on nightly?
- has your toolchain got the `rls-preview`, `rust-analysys` and `rust-src` components installed?
- can you start `rls` from a terminal\cmd?

Bear in mind not all `nightly` have the `rls-preview` component available and you might have to pick one.

**Comment by anb0s** [comment]
Yes i've opened the preferences and did not changed anything (all settings are default), because it worked before upgrading corrosion.

- i've two PCs / workspaces: one Rust on stable and second on beta --> same problem.

OK, it means the new corrosion versions need also nightly Rust with new rls etc. --> i will revert my last upgrade of corrosion for stable workspace and switch from beta to nightly for the second workspace...

Thanks!

**Comment by anb0s** [comment]
Tried to use Eclipse for changing to nightly:
![image](https://user-images.githubusercontent.com/95811/45567355-dcc07280-b859-11e8-8eaf-87133b62ff8f.png)

After selecting Nightly, Apply is not possible and it shows "Install missing rls component in Rustup"

Button Install just opens a WebBrowser with "https://rustup.rs/". So changing Toolchain and Install does not work throught Eclipse.
![image](https://user-images.githubusercontent.com/95811/45567559-66704000-b85a-11e8-8f3a-84c75c043e7c.png)

**Comment by anb0s** [comment]
Executed at command line:
`rustup update`
`rustup default nightly`
`rustup component add rls-preview rust-analysis rust-src`

Restarted Eclipse and now Preferences can be changed:
![image](https://user-images.githubusercontent.com/95811/45567782-04640a80-b85b-11e8-8421-b39e6cb21681.png)

Ctrl+O is working now! The Outline view is empty, but no exceptions anymore.

![image](https://user-images.githubusercontent.com/95811/45567884-4d1bc380-b85b-11e8-81d2-7f0c745cb656.png)

**Comment by anb0s** [comment]
Verified that it works with:
```
nightly-x86_64-pc-windows-msvc (default)
rustc 1.30.0-nightly (90d36fb59 2018-09-13)
```
but does not work with (have same exceptions):
```
nightly-x86_64-pc-windows-gnu (default)
rustc 1.30.0-nightly (90d36fb59 2018-09-13)
```
because 
```
C:\WINDOWS\system32>rustup component add rls-preview rust-analysis rust-src
error: component 'rls-preview' for 'x86_64-pc-windows-gnu' is unavailable for download
```

**Comment by anb0s** [comment]
Thank You for your help!

Maybe a brief information about the need of nightly channel and msvc toolhain only, because of "rls-preview" would be good for beginners.

**Comment by norru** [comment]
Yep, it's a bit rough on the edges :) + @mickaelistria to update the docs?

**Comment by mickaelistria** [comment]
Even better, if you think it makes sense, improve the preference page and popup with hints you believe would have been more helpful.

**Comment by Fermi-4** [comment]
Could not determine GDB version using command: rust-gdb --version
error: the 'rust-gdb.exe' binary, normally provided by the 'rustc' component, is not applicable to the 'nightly-x86_64-pc-windows-msvc' toolchain

Thoughts?
