### ISSUE TITLE
Linkable/clickable file paths from Cargo output in Console

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#132]
Even if the RLS does it in the background, It would be great to have the output parsed in the Console (for cargo build and cargo run) so that file names and line numbers are transformed into clickable links, for instance:

```
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
```

```
warning: where clauses are not enforced in type aliases
  --> src/main.rs:58:2
   |
58 |     D: gfx::Device,
   |     ^^^^^^^^^^^^^^
   |
```

**Comment by mickaelistria** [comment]
It seems to be a matter of adding an extension to https://help.eclipse.org/2018-12/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_ui_workbench_texteditor_hyperlinkDetectors.html .
This would need to be in Corrosion as the given path are not absolute and specific to a cargo build.

**Comment by norru** [comment]
RustDT had this working, perhaps we can graft?

**Comment by mickaelistria** [comment]
RustDT seems to use a deprecated framework (Melnorme) for that. We shouldn't try to reuse this framework and it seems more sustainable and easier to reimplement hyperlink detection from scratch instead of reusing deprecated code.

**Comment by norru** [comment]
I see.
