### ISSUE TITLE
GDB Mingw64 doesn't start

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#138]
Tested on 
- Windows 10 + mingw64
- Eclipse Rust 2018-09 latest package (installed from scratch)

gdb 8.2 is not recognized:

![image](https://user-images.githubusercontent.com/889291/46159279-d083de80-c277-11e8-8520-b11e9ff35b1d.png)

```
> gdb --version

GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
It does look like the output of  `--version` has changed since 8.1

```
> gdb --version
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
```

As a side note, this is also a workaround to the fact that `rust-gdb` is not available in `windows-gnu` toolchains.

**Comment by norru** [comment]
Nevermind, version is a red herring, downgrading to `8.1.1` doesn't solve the problem:

`
>gdb.exe --version
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

>where gdb.exe
C:\msys64\mingw64\bin\gdb.exe
`

**Comment by anb0s** [comment]
see #93 same issue at windows...

**Comment by norru** [comment]
With similar settings (but `rust-gdb` installed) Debugging works correctly on Ubuntu and Devuan.

**Comment by anb0s** [comment]
see #149 may be the workaround with .gdbinit adaptations does the trick with prety-printers and MinGW GDB...

**Comment by anb0s** [comment]
@norru it works with modified .gdbinit file for me too, here with MinGW GDB 8.2 :)

see https://github.com/eclipse/corrosion/issues/149#issuecomment-431141419

**Comment by justdak** [comment]
@anb0s @norru just for test, could you please do the following steps:

1. rename \plugins\**org.eclipse.cdt.core.win32.x86_64**_5.4.2.201811241055\os\win32\x86_64\spawner.dll (for example to ____spawner.dll)
2. Set path to mingw64 gdb.exe in launch configuration.
3. Try to launch debug

It should works but it is not the solution. 

see #188
