### ISSUE TITLE
[Debug] [Linux] [Arch] "Debug As -> Rust Project" does not work 

### ISSUE THREAD

**Issue by anb0s** [eclipse/corrosion#139]
Select project and use "Debug As -> Rust Project" shows just:
![image](https://user-images.githubusercontent.com/95811/46407126-1aecdb80-c70e-11e8-9030-75e52d79a5e6.png)

**Versions**
- OS: Linux ... 4.18.9-1-MANJARO SMP PREEMPT ... x86_64 GNU/Linux
- Rust: rustc 1.31.0-nightly (2bd5993ca 2018-10-02)
- rust-gdb: GNU gdb (GDB) 8.2
- Eclipse: Eclipse IDE for C/C++ Developers, Version: 2018-09 (4.9.0), Build id: 20180917-1800
- Corrosion: Rust edition in Eclipse IDE 0.1.0.201809141024

**Comment by anb0s** [comment]
see #140 with GDB 8.1 at Debian it works!

**Comment by akurtakov** [comment]
To help further investigation - debug works for me with GDB 8.2  on Fedora 29.

**Comment by aario** [comment]
Seems like gdb version doesn't have anything to do with this.
```
> gdb --version
GNU gdb (Debian 8.1-4+b1) 8.1
.
.
.
> rustc --version
rustc 1.28.0-nightly (29ffe51e3 2018-05-23)
```
````
Eclipse IDE for Rust Developers

Version: 2018-09 (4.9.0)
Build id: 20180917-1800
```
Still the same error.

**Comment by aario** [comment]
Here the solution provided worked:
https://github.com/eclipse/corrosion/issues/93#issuecomment-422373923
It's right clicking on the project and selecting Run/Debug As and then Going to configuration dialog and enter an absolute path starting with `/` as the program to start when debugging.

**Comment by mickaelistria** [comment]
It seems like patch from #148 could fix this one. Can you please try again with latest snapshot? Update-site is http://download.eclipse.org/corrrosion/snapshots

**Comment by anb0s** [comment]
Updated Corrosion to "0.1.0.201810161046" and "Debug As -> Rust Project" just works without any workarounds now!

Thanks @Boereck and @mickaelistria
