### ISSUE TITLE
[Debug] [Linux] [Debian] "Debug As -> Rust Project" does not work

### ISSUE THREAD

**Issue by anb0s** [eclipse/corrosion#140]
Select project and use "Debug As -> Rust Project" shows just:

**Versions**
- OS: Linux ... 4.17.0-3-amd64 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux
- Rust: rustc 1.31.0-nightly (2bd5993ca 2018-10-02)
- rust-gdb: GNU gdb (Debian 8.1-4) 8.1
- Eclipse: Eclipse IDE for Eclipse Committers, Version: Photon Release (4.8.0), Build id: 20180619-1200
- Corrosion: Rust edition in Eclipse IDE 0.1.0.201809141024

**Comment by anb0s** [comment]
Just verified it again and it works with GDB 8.1 @Debian it looks like GDB 8.2 is not supported...

**Comment by norru** [comment]
I have seen the same behaviour with Windows + MinGW64
