### ISSUE TITLE
Rust Debug configuration is missing "Arguments" tab

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#151]
This makes debugging of specific input command line options impossible with the native Rust debugger.

Current (Rust):

![selection_085](https://user-images.githubusercontent.com/889291/46953113-cab63780-d084-11e8-8203-54d9f1ab9900.png)

Expected (C++ debugging):

![selection_084](https://user-images.githubusercontent.com/889291/46953154-eb7e8d00-d084-11e8-995e-e8f8b5cd0088.png)

**Comment by akurtakov** [comment]
Please verify with snapshot repo http://download.eclipse.org/corrosion/snapshots/ that this satisfies your needs or let me know if there is smth missing.

**Comment by norru** [comment]
@akurtakov, @mickaelistria I've tried the snap, it's fixed, many thanks! :)
