### ISSUE TITLE
Zipped update site contains wrong directory structure

### ISSUE THREAD

**Issue by Boereck** [eclipse/corrosion#155]
Hey,

Recently I downloaded the repository.zip for the latest snapshot release. Unfortunately zip file cannot be used directly as an update site, because it does not contain the p2 repo directly. Instead, it has the directory prefix `repository\target\repository\`. Is there a reason why the Jenkins 'Deploy' stage zips up the repository (which introduces the folder structure inside the zip file) instead of just copying the `repository/target/repository-X.Y.Z-SNAPSHOT.zip` file already produced as part of the build? If not, we could simply replace the last zip command by `cp repository/target/repository-*-SNAPSHOT.zip /home/data/httpd/download.eclipse.org/corrosion/snapshots/repository.zip`

**Comment by mickaelistria** [comment]
No good reason in particular. Feel free to update the Jenkinsfile to get better results.
