### ISSUE TITLE
Code templates: tabs vs. spaces

### ISSUE THREAD

**Issue by Boereck** [eclipse/corrosion#158]
Hi all, 
I realized in the code templates tabs are used for indentation. The rust-fmt (style)[https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md#formatting-conventions] is 4 spaces. Even when in the preferences `General > Editors > Text Editors` the option "Insert spaces for tabs" is selected the template text will be inserted with tabs instead of spaces.

Should the template mechanism be improved to replace tabs with spaces when the Text Editor configuration is configured this way? Or should we replace the tab in our templates with spaces?

**Comment by mickaelistria** [comment]
Ideally, we should probably apply the Text Formatting preferences after insertion of templates.
But pragmatically, fixing the templates seems to be something to do anyway, and well enough at tte moment ;) So I suggest the later one.

**Comment by Boereck** [comment]
Fixed with #157
