### ISSUE TITLE
Annoying behavior when auto-closing quotes or brackets

### ISSUE THREAD

**Issue by ctron** [eclipse/corrosion#163]
Assume you type in: `let foo = "bar"`. When you enter this, directly into the editor, then you will get:

~~~
let foo = "bar";""
~~~

As the second `"` will not be detected as a closing `"`, but rather start a new one and add an additional closing one. This is super annoying, and is does work like a charm in JDT.

**Comment by ctron** [comment]
Btw, the behavior is true for brackets (and maybe other things) as well.

**Comment by norru** [comment]
I found autoclosing to be unreliable so I disabled it in `Preferences -> TextMate -> Language Configurations -> org.eclipse.corrosion.rust -> Auto Closing Pairs -> (disable) Enable auto closing brackets`

**Comment by mickaelistria** [comment]
Improvement to detect a closing bracket and not re-insert it should be report to TM4E project.

**Comment by mickaelistria** [comment]
I've opened https://github.com/eclipse/tm4e/issues/192 in TM4E about it. @norru @ctron Can you please have a look at the proposal I put there and comment whether you think it'd cover your use-cases?

**Comment by mickaelistria** [comment]
@ctron Thanks. You can install latest snapshot of tm4e from https://download.eclipse.org/tm4e/snapshots/ . Then re-enable the auto-closing if you disabled it and report how happy you are ;)

**Comment by mickaelistria** [comment]
Fixed upstream in TM4E.
