### ISSUE TITLE
Indexing stuck at 0%, requires IDE restart

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#164]
After working for a while, Indexing stops working at all with the following outcome. As a result I have to restart the IDE several times per hour.

![selection_030](https://user-images.githubusercontent.com/889291/47956069-fdbe5d80-df96-11e8-9466-24944db7cfa3.png)

**Comment by norru** [comment]
Trying to see if there is anything wrong in JStack but nothing so far.

**Comment by norru** [comment]
If it helps, I have observed this behaviour only in projects which use `bindgen` (possibly any custom `build.rs` script?).

**Comment by ngortheone** [comment]
I have pretty consistent way of reproducing it with opening https://github.com/jwilm/alacritty
And as @norru mentioned - yes it has custom `build.rs` and `bindgen`
Question - is there a way to fix/avoid that?

**Comment by norru** [comment]
@ngortheone Having a reproducible case will definitely help. I haven't found a workaround yet but I have not encountered this problem lately - perhaps an "accidental fix" did it for me?

**Comment by norru** [comment]
Just happened again

[jstack_16687.txt](https://github.com/eclipse/corrosion/files/2667922/jstack_16687.txt)

**Comment by norru** [comment]
Not seen this for a while. Closing.
