### ISSUE TITLE
Ctrl+Space not working in Eclipse IDE for Rust developers package 2018-12 M3

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#179]
I'm testing the package from https://www.eclipse.org/downloads/packages/release/2018-12/m3 .
I create a new Rust project and try to get the completion with Ctrl+Click, I see nothing, it seems like the shortcut is not bound. If I type `.` which is an auto-activation trigger, I get some results.

**Comment by mickaelistria** [comment]
Note that it doesn't seem to relate to RLS. For example.
1. On a new line, type `S` and then Ctrl+Space => nothing happens :(
2. then type `.` => templates proposals show up (ok, why not)
3. Move left (backspace or left arrow), just after `S` => See RLS proposal for `String` and others.

It's really that Ctrl+Space seems unplugged.

**Comment by mickaelistria** [comment]
Another way to see the completion working (and again narrowing the issue to Ctrl+Space shortcut): Go wherever there is context for a good completion, then `Ctrl+3 > C/C++ quick assist (basic)` actually invoke the editor's content assist and shows the proposals for RLS.

**Comment by mickaelistria** [comment]
After some restarts and nothing really different from usual, it now works again...

**Comment by mickaelistria** [comment]
I couldn't reproduce it with later versions...

**Comment by Disgust** [comment]
Have the same issue
Eclipse IDE for Rust Developers

Version: 2019-03 (4.11.0)
Build id: 20190314-1200

**Comment by Disgust** [comment]
Solved by moving Ctrl+Space binding from Content Assist to C/C++ Content Assist (Basic Proposals)
