### ISSUE TITLE
Remove Rust perspective

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#181]
The Rust perspective seems to bring nothing over default Resources and Debug ones. It would probably be better to remove it if it doesn't add value.

**Comment by akurtakov** [comment]
Fully agreed. @norru @Boereck  wdyt?

**Comment by serjiokov** [comment]
Hello, I think specific perspective may exist for Rust Development in further it will aggregate some rust specific viewers.  
I've prepared fix to switch Rust Perspective from New Project Wizard.

**Comment by mickaelistria** [comment]
I think as long as there are no specific view, we should bother with the perspective.
Extra views could also be added by default as perspective extensions on the resource views if necessary.
If we need to re-implement a perspective later, it's all fine. It will be even better as we'll have a use-case for it to drive to a better implementation, while we currently have no reason for it.

> I've prepared fix to switch Rust Perspective from New Project Wizard.

What's the added value over current state?

**Comment by serjiokov** [comment]
### What's the added value over current state?
I mean prepared on the local branch: 
- in plugin.xml :  preferredPerspectives="org.eclipse.corrosion.rustPerspective"
- in NewCargoProjectWizard: usage of BasicNewProjectResourceWizard.updatePerspective(configuration);

**Comment by mickaelistria** [comment]
At the moment, I think it's better for end-users and maintainers to remove the perspective and stick to the Resource one; unless we have a compelling use-case for it.
That doesn't prevent from re-introducing a perspective later when we think there is enough value to justify it, but at the moment, this doesn't seem to be the case.

**Comment by serjiokov** [comment]
Ok, we can define defualt or prefered perspective like Resouces or C++ or you other, (could you suggest?) and swirch to it.

**Comment by norru** [comment]
@serjiokov I would not like C++ as it would be misleading. Would prefer Resource..

**Comment by serjiokov** [comment]
Resource perspective quite simple without launch toolbar. It is not friendly to me. Any ideas?

**Comment by serjiokov** [comment]
![ice_screenshot_20190116-164549](https://user-images.githubusercontent.com/32031248/51253175-ad0fab80-19ae-11e9-8530-cf6eec643c1b.png)

**Comment by norru** [comment]
I'm not familiar with this. Is it not possible to pre-add the launch toolbar to the existing perspective?

**Comment by norru** [comment]
@mickaelistria @serjiokov I am no longer sure removing the perspective is a good idea - the problem is that users would expect **something** to contain the Rust environment, and that something for Eclipse users is possibly expected to be a pre-defined "custom" perspective.

There is some sort of "branding" power we'd lose if we removed it.

Perhaps we should reconsider?

**Comment by mickaelistria** [comment]
> There is some sort of "branding" power we'd lose if we removed it.

Do we (developers) and users need this power right now? Maintaining such power has a cost for us (which in that case I'm not likely to pay); it also has a cost for users because of multiplication of perspectives which some users hate.
In my experience, and I did work a lot on branded plugins in the IDE with JBoss Tools, users actually prefer simplicity over branding which is perceived as noise unless it provides them added-value, ie make them often more productive.

**Comment by norru** [comment]
> (which in that case I'm not likely to pay)

Fair enough, scarce resource means prioritization. However, we may have revisit the perspective implementation in a few months and see if there is any feedback on the lack of a "dedicated" space.

**Comment by mickaelistria** [comment]
I've opened #219 and #220 to cover sub-parts of the discussion. Let's try to keep things separated for easier tracking and progress.

**Comment by mickaelistria** [comment]
Done a few months ago.
