### ISSUE TITLE
First Run of a project should show the Run Configuration page

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#184]
The Launch shortcuts for Corrosion should force users to see the Launch/Debug configuration at least once. When never started, the Run As... or Debug As... shortcuts should show the Launch dialog with a preconfigured launch config and allow users to tweak things like CLI parameters. Then, once created, a new (or several) shortcut could be added to directly run the existing launch(es) for the given resource.

**Comment by akurtakov** [comment]
This is against the workflow for e.g. JUnit tests run so not going to work on that here.
