### ISSUE TITLE
Missing RLS config file?

### ISSUE THREAD

**Issue by theDragonFire** [eclipse/corrosion#186]
I have installed Eclipse for Rust and would like to use it for development. However, the content assist by RLS (such as code completion and highlighting) doesn’t work. RLS can't seem to find racer or rustc. As I was looking at the settings for Rust (Window > Preferences > Rust), I noticed that the RLS config is pointing to a nonexistent file at ~/.cargo/rls.conf. How do I get the rls.conf file?

I am currently using Ubuntu 18.04 and Eclipse Photon.

**Comment by mickaelistria** [comment]
Is the .cargo folder already existing?
@norru Can you help?

**Comment by theDragonFire** [comment]
The .cargo folder does exist. It is just the rls.conf file that does not exist.

**Comment by norru** [comment]
I have also just noticed that you are using Eclipse Photon - I would suggest you upgrade to Eclipse 2018-09 (if Eclipse hasn't done that for you) as there is not much of Corrosion development taking place in the older version.

**Comment by theDragonFire** [comment]
So I seem to be getting one recurring warning and one recurring error relating to corrosion. The warning says `RLS settings for Corrosion path not found at /home/dragonfire/.cargo/rls.conf`, which you said isn't a problem. The error says `org.eclipse.lsp4j.jsonrpc.ResponseErrorException: missing field 'codeActionKind'`.

The only thing I could find in the log file that mentions anything like 'codeActionKind' is this recurring line:

    org.eclipse.corrosion.rls to LSP4E: {
      "jsonrpc":"2.0", "id":1, "result": {
        "capabilities": {
          [...]
          "codeActionProvider":true
          [...]
        }
      }
    }

and

    LSP4E to org.eclipse.corrosion.rls: { 
        [...]
        "params":{
         [...]
         "capabilities":{
           [...]
           "textDocument":{
             [...]
             "codeAction":{},
             [...] 
           }
         }
        [...]
      }
    }

Does this help?

**Comment by theDragonFire** [comment]
Is there a way for Eclipse to automatically update? Or do I have to completely reinstall it?

**Comment by norru** [comment]
> org.eclipse.lsp4j.jsonrpc.ResponseErrorException: missing field 'codeActionKind'.

This does ring a bell, there was a bug reported in the Language Server Protocol handler in Eclipse, which was fixed in:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=541851
https://git.eclipse.org/c/lsp4e/lsp4e.git/commit/?id=6cc786f0d9bc1c12b818f7677796e2b4efdefbef

@mickaelistria is the version of the LSP4E containing this fix not delivered with the latest Eclipse repo?

**Comment by mickaelistria** [comment]
> is the version of the LSP4E containing this fix not delivered with the latest Eclipse repo?

Indeed, we didn't update the .target file to latest version of LSP4E, so currently, the latest release from September (containing this bug) is shipped.
It's all fine in the SimRel repo but not in Corrosion snapshot repo. I'll update it immediately, and since it's only transitive dependencies and actual bundles we produce shouldn't change, we may consider just replacing the 0.3.0 repo with a newer one; or ask for a 0.3.1.

**Comment by norru** [comment]
@theDragonFire if it helps, I have an identical setup to yours (Ubuntu 18.04 + Eclipse 2018-09 + Corrosion snapshots) and I use it daily so if you run into other obstacles I can probably reproduce them quickly :)

**Comment by norru** [comment]
If it is the case, then the quickes fix for @theDragonFire is to also get the bleeding edge version of Corrosion from http://download.eclipse.org/corrosion/snapshots/

**Comment by mickaelistria** [comment]
At the moment, the quickfix would be to use the latest build of "Eclipse IDE for Rust developers"

**Comment by theDragonFire** [comment]
So I have installed Eclipse 2018-09. I used the above links to get the bleeding edge version of lsp4e and Corrosion. However, when I try to install lsp4e, it won't install 'Generic and Extensible Text Editor' and 'Gson', giving me this error:

    Your original request has been modified.
      "Gson: Google Json Library for Java" will be ignored because a newer version is already installed. 
      "Generic and Extensible Text Editor" is already installed, so an update will be performed instead.
    Cannot complete the install because of a conflicting dependency.
      Software being installed: Generic and Extensible Text Editor 1.1.200.v20180921-0739 (org.eclipse.ui.genericeditor 1.1.200.v20180921-0739)
      Software currently installed: Eclipse Platform 4.9.0.v20180906-1121 (org.eclipse.platform.feature.group 4.9.0.v20180906-1121)
      Only one of the following can be installed at once: 
        Generic and Extensible Text Editor 1.1.200.v20180921-0739 (org.eclipse.ui.genericeditor 1.1.200.v20180921-0739)
        Generic and Extensible Text Editor 1.1.100.v20180824-1616 (org.eclipse.ui.genericeditor 1.1.100.v20180824-1616)
      Cannot satisfy dependency:
        From: Eclipse Platform 4.9.0.v20180906-1121 (org.eclipse.platform.feature.group 4.9.0.v20180906-1121)
        To: org.eclipse.equinox.p2.iu; org.eclipse.ui.genericeditor [1.1.100.v20180824-1616,1.1.100.v20180824-1616]

I am also still getting the previously mentioned error about 'codeActionKind'.

**Comment by norru** [comment]
> I am also still getting the previously mentioned error about 'codeActionKind'.

This probably means the latest LSP4E is not being installed.

Do you want to attempt to install  the latest Tm4e (TextEditor) snapshots as well?

http://download.eclipse.org/tm4e/snapshots/

**Comment by theDragonFire** [comment]
I've tried all of that and for some reason it isn't working. Any other ideas?

If not, I guess I'll wait until [Eclipse 2018-12](https://projects.eclipse.org/releases/2018-12) comes out. Hopefully that will fix it. I'll report back then.

**Comment by mickaelistria** [comment]
You can already try Eclipse 2018-12 at https://www.eclipse.org/downloads/index-developer.php . Pick the package directly (not the installer). It does contain the latest version of LSP4E and Corrosion.

@norru: Corrosion has a "lax" dependency on LSP4E versions. As a result, if a compatible version of LSP4E is already installed, the installation or upgrade will not necessarily force an update of it; so the bug is still here. We need Corrosion to be a bit more strict regarding requirements on LSP4E to reduce the probability of such issues.

**Comment by theDragonFire** [comment]
I installed Eclipse 2018-12 and everything works perfectly! Thank you so much @norru and @mickaelistria for spending your time helping me figure this out! Now that it works, I'll be able to be a lot more productive.

**Comment by norru** [comment]
Hi @theDragonFire, I have managed to reproduce your problem 

- make sure you have a recent/working toolchain with RLS (tested with nightly 2018-12-13)
- download and install Eclipse IDE For Rust Developer from https://www.eclipse.org/downloads/packages/release/2018-09/r/eclipse-ide-rust-developers-includes-incubating-components
- start the installed Eclipse. This will not work out of the box and will exhibit the problem you reported with `codeActionKind`. Ignore it for now.
- Help -> Install new software

Do not press `Next >`. Instead, add the following three sites via `Add...` or `Manage...`

Corrosion Snapshots - http://download.eclipse.org/corrosion/snapshots/
TM4E Snapshots - http://download.eclipse.org/tm4e/snapshots/
LSP4E Snapshots - http://download.eclipse.org/lsp4e/snapshots/

- Close the "Install" window
- Help -> Check for updates
- accept the proposed selection (in my case Corrosion wanted to upgrade)
- press Next/Finish to the end
- restart Eclipse when prompted

**Comment by sabdelhay** [comment]
@norru thank you, you're a live saver 👍

**Comment by worikgh** [comment]
I am having the exact same problem but with 
```
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
```
I have tried: `$  touch ~/.cargo/rls.conf` but does not help.
I have read the above but find it very opaque.

**Comment by worikgh** [comment]
`$ rustup component add rls`

**Comment by jorn-p-l** [comment]
The solution is to create the rls.conf file

and using the command in the console.

```
PS C:\Users\andre\.cargo\bin> .\rls.exe
error: 'rls.exe' is not installed for the toolchain 'stable-x86_64-pc-windows-msvc'
To install, run `rustup component add rls --toolchain stable-x86_64-pc-windows-msvc`
PS C:\Users\andre\.cargo\bin> rustup component add rls --toolchain stable-x86_64-pc-windows-msvc
```

After downloading the additional file, the problem disappeared.
