### ISSUE TITLE
Cannot start debugging because the Working Directory is empty

### ISSUE THREAD

**Issue by justdak** [eclipse/corrosion#188]
I have to set Working Directory every time I open Debug Configurations Window. 
It won't save after I click Apply button and Close the window in currentt version 2018-09 (4.9.0) (Build id: 20180917-1800):

![image](https://user-images.githubusercontent.com/44570153/50044530-dda1b400-0095-11e9-86db-ebb5d593a6d5.png)

The main reason is that Arguments Tab is already has the Workind Directory field:

![image](https://user-images.githubusercontent.com/44570153/50044715-ee9ff480-0098-11e9-97a8-5283982a46cc.png)

and WorkingDirectoryBlock::performApply() method delete working directory value from the configuration (set it to null):

![image](https://user-images.githubusercontent.com/44570153/50044750-4e969b00-0099-11e9-8f2c-1b95808746aa.png)

Do we need to duplicate this setting on the first page?

**Comment by justdak** [comment]
I can reproduce it on latest build: Version: 2018-12 RC1 (4.10.0RC1), Build id: 20181206-2346

As I wrote above, I already investigated this issue using Eclipse for Commiters and found out that the **main tab** and **Arguments tab** have 2 different Working Directory fields. The "Apply button" code for Argument tab sets Working Directory value to null. So it won't save after user click Apply button and close the debug configuration window. 

I think there is no reason to duplicate this setting on the first page.

**Comment by mickaelistria** [comment]
You analysis is most likely correct. Do you feel like you could submit a patch for it?

**Comment by justdak** [comment]
Sure, just to clarify - it is better to delete Working Directory from main tab or Arguments tab? What do you think?

**Comment by mickaelistria** [comment]
I don't have a strong opinion here and it's something we can easily change later if necessary. So I let you choose whichever your prefer ;)

**Comment by justdak** [comment]
Ok,  I decided to remove Working Directory from main tab. Please see #189 and review it. 
With this fix I can debug rust projects with mingw64 GDB with no problems.

**Comment by anb0s** [comment]
@justdak see #138 and #149, are you using MinGW64 gdb.exe with the described trick for python pretty printers in .gdbinit or is there usable "rust-gdb.exe" available now?

**Comment by justdak** [comment]
@anb0s I'm using mingw64 gdb without any trick:

![image](https://user-images.githubusercontent.com/44570153/50183872-75b4cd00-0324-11e9-85f5-e59f59213088.png)

Please note that I have no error in Eclipse for Committers  + corrosion source code from github.

And I have error in Version: 2018-12 RC1 (4.10.0RC1) Build id: 20181206-2346 with settings above:

![image](https://user-images.githubusercontent.com/44570153/50183826-469e5b80-0324-11e9-9df6-0bd66fc33b0c.png)

**Comment by mickaelistria** [comment]
@justdak great finding! So it seems like Corrosion works when you start a workspace from source, but similar code fails when packaged? That could be a good hint. Do you think you could find a solution to it? Therr is a long standing issue reported about it and your case seems to shed some light on possible causes.

**Comment by justdak** [comment]
@mickaelistria sure, I have just played with it a little bit and and found out that we have problem with **getLaunchEnvironment()** method in **RustGDBLaunchWrapper.java**:

![image](https://user-images.githubusercontent.com/44570153/50257545-af610300-040c-11e9-9d1e-5bfdf5099f8f.png)

Looks like **getLaunchEnvironment()** breaks the **PATH** variable. And gdb works fine, if I change **launchEnvironment** variable value to "new String[0]" during the debugging proces.

I'd like to continue investigate this issue. :)

**Comment by anb0s** [comment]
@justdak Thanks! It works with Eclipse Commiters (without CDT)

**Comment by justdak** [comment]
@anb0s Corrosion build will work too if you delete or rename  eclipse\plugins\org.eclipse.cdt.core.win32.x86_64_5.4.2.201811241055\os\win32\x86_64\spawner.dll from it. But this is workaround. The real fix is here - #201

**Comment by anb0s** [comment]
Thanks, i'm waiting for the nightly build with the fix then!

**Comment by mickaelistria** [comment]
#201 was merged and built including it took place. Can you please install the most recent build from http://download.eclipse.org/corrosion/snapshots , try it and report whether it fixes this issue?

**Comment by justdak** [comment]
@anb0s please let me know if recent build from http://download.eclipse.org/corrosion/snapshots fix your problem with mingw64 GDB.
