### ISSUE TITLE
Pressing '(' closes enclosing parentheses instead of adding '('

### ISSUE THREAD

**Issue by theDragonFire** [eclipse/corrosion#198]
I have code like this:
```rust
foo(String::from[cursor is here])
```
and I press the '(' key to open a pair of parentheses, expecting this to be the result:
```rust
foo(String::from([cursor is here]))
```
Instead, it closes the outer parentheses, with the result being this:
```rust
foo(String::from)[cursor is here]
```
Is there some way to change this? It slows me down to have to delete the closing parentheses, then add them back in.

**Comment by theDragonFire** [comment]
Also, it seems that this *should* happen when you press ')', but it doesn't.

**Comment by theDragonFire** [comment]
Done. Should I close this issue?

**Comment by mickaelistria** [comment]
Thanks for reporting upstream.
let's keep it open here to track the cascading of resolution from TM4E to Corrosion.

**Comment by norru** [comment]
@theDragonFire if you have bandwidth to test this, this is a good time.

**Comment by theDragonFire** [comment]
Am I testing if it works in Corrosion? Because if I am, I have used Corrosion with the changes made to TM4E and it works correctly.

**Comment by norru** [comment]
Thanks! :+1:
