### ISSUE TITLE
Test suite for preferences

### ISSUE THREAD

**Issue by LucasBullen** [eclipse/corrosion#2]
A test suite to confirm the functionality of getting/setting the default toolchain and UI of the preferences page

**Comment by mickaelistria** [comment]
I suggest we just close bugs that are about adding test suites. Adding test suites is always welcome, and it doesn't require to be tracked. Actually, there are even metrics of software quality/cost that suggest that if a feature is shipped and working (no known issue), it's not worth adding tests after it's shipped, it's just worth adding tests when adding features or fixing bugs on it.
