### ISSUE TITLE
Cannot use Rust if installed in directories containing spaces

### ISSUE THREAD

**Issue by mwhapples** [eclipse/corrosion#202]
I have found that should rust be installed in a directory containing spaces, then corrosion will not be able to use the rust installation.

To give my specific example. I am using Windows 10 X86_64. The user directory is "C:\users\Michael Whapples\". I had installed rust using rustup, letting it install in the default location under the user home directory. When I tried to use corrosion, when I went to preferences to configure the rust paths, I found even when the rust installation directories had been explicitly set there was still an error message about not being able to use rust (cannot remember the exact error message, either not being able to find the executable or obtain version information) and the apply button was not available.

I realised that the space in the directory path may have been causing problems, so I uninstalled rust, set RUSTUP_HOME and CARGO_HOME to a path without spaces (eg. "C:\rust\") and reinstalled rust via rustup. Using corrosion with rust installed in a location without spaces in the path worked fine.

At the moment I have only been able to test this issue on Windows, it may or may not exist on other platforms.

**Comment by justdak** [comment]
I think it is easy to fix this bug.

The _**getProcessForCommand**_ function uses **_ProcessBuilder_** and it already can deal with spaces.  But this functionality breaks with function call like:
```
return matchPattern.matcher(getOutputFromCommand(commandPath + " --version")).matches(); 
```
Instead, it should be something like:
```
return matchPattern.matcher(getOutputFromCommand(new String[] { commandPath, "--version" })).matches();
```

Some modification of _**getProcessForCommand**_ function is also needed.

**Comment by mickaelistria** [comment]
@justdak Interested.in submitting a PR?

**Comment by justdak** [comment]
@mickaelistria ok, I will try to create patch for this, if there are no other people who want to fix it. :)

**Comment by norru** [comment]
@LucasBullen ?

**Comment by mickaelistria** [comment]
@norru Lucas is a student, he's back to university and isn't working for Red Hat since last summer. So he's not very likely to react.
If you have some time to review @justdak 's PR, that would be great.

**Comment by norru** [comment]
@mickaelistria good to know about @LucasBullen 

@justdak I think I have spotted a potential problem with the usage of `bash -c`. Will follow up shortly.

@mickaelistria do you know why we are using `bash -c` wrapper execs rather than spawning subprocesses directly?

**Comment by mickaelistria** [comment]
IIRC, using `bash` allows to resolve the PATH, and helps is better parsing the arguments, but I'm not 100% sure and if we can find something reliable without it, I'm all for it.
