### ISSUE TITLE
Make environment variable handling in RustGDBLaunchWrapper more robust

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#207]
At the moment, the way `PATH` env var is handled when running GDB is a bit iffy and plays fast and loose with regard to escaping special characters/quoting.

We need to write more thorough tests and make the implementation more robust. As the user base grows, it will become more likely that we'll hit weird edge cases in user's file and directory naming.

**Comment by mickaelistria** [comment]
Do you know some steps to reproduce such issue ?

**Comment by norru** [comment]
I can think of some weird stuff :) there is no rush for this though. It's just a placeholder for tracking. We can mark as low-priority if you want.

**Comment by mickaelistria** [comment]
I think we should basically not even set the PATH and rely on the "parent" environment instead of tweaking it. That would also bring more consistency with default CLI behavior.

**Comment by mickaelistria** [comment]
Should be fixed with https://github.com/eclipse/corrosion/commit/6e4299ada4ca23d16131ba595d55e948bfdd49b0
