### ISSUE TITLE
ctrl+/ shortcut comment out line

### ISSUE THREAD

**Issue by gkorland** [eclipse/corrosion#215]
ctrl+/ shortcut comment out line not working

**Comment by mickaelistria** [comment]
Shortcut is Ctrl+Shift+C ( https://github.com/eclipse/tm4e/blob/master . Can you please try it?/org.eclipse.tm4e.languageconfiguration/plugin.xml#L91). You can discover it with Quick Fix (Ctrl+3) then typing "comment" and you'll see the list of commands with their shortcut.

**Comment by mickaelistria** [comment]
Ctrl+/ is implemented by each language plguiugin and doesn't work.for HTML, XML, Bash... TM4E opted for something more portable and Corrosion inherits from it.

**Comment by norru** [comment]
> something more portable

I'm puzzled. Why is `Ctrl+/` (or `Ctrl+Shift+/`) any less portable than `Ctrl+Shift+C`?

**Comment by mickaelistria** [comment]
> Ctrl+3 says that ctrl+/ is used for comment toggle

Ok, that's strange.
Does Ctrl+Shift+C work for you? Ctrl+/ may come from another plugin, if it doesn't work we need to investigate where it comes from so it's not enabled on the Rust editor.

> I'm puzzled. Why is Ctrl+/ (or Ctrl+Shift+/) any less portable than Ctrl+Shift+C?

It's mnemotecnis. `C` for Comment is universal. For users of languages that do not use `/` for comment, `Ctrl+/` is harder to guess/remember. But nothing would prevent Corrosion from adding the Ctrl+/ as shortcut too, it's just not something that should be done in TM4E.

**Comment by norru** [comment]
> It's mnemotecnis. 

Is it something that has been researched with actual experiment, or just a guess? I'd have never guessed the keystroke unless someone told me.

**Comment by mickaelistria** [comment]
>  Is it something that has been researched with actual experiment, or just a guess?

Let's say it's just a guess. But Ctrl+Shift+C is already a working shortcut in all editors (including Java, legacy XML, HTML and so on) so it's the real universal shortcut in the Eclipse IDE. Ctrl+/ is just enabled for some languages where "/" is a comment character.
So TM4E being generic goes by default for the generic shortcut for the sake of consistency with the whole IDE.
If Corrosion wants to implement another additional shortcut, why not.

**Comment by norru** [comment]
> If Corrosion wants to implement another additional shortcut, why not.

+1 for having 2 shortcuts for this. I think this will help people transitioning from Java to Rust. I might have a look at this, if there is no other taker. @gkorland?

While I'm at it I could add another shortcut for the `Rename` refactoring (`F2` vs `Shift+Alt+R` or something always trips me up).

**Comment by norru** [comment]
I've got this working in a local branch. Will submit PR.

**Comment by norru** [comment]
> Ctrl+/ may come from another plugin

Might be CDT

**Comment by norru** [comment]
https://github.com/eclipse/corrosion/pull/227

**Comment by mickaelistria** [comment]
Fixed with 02a0f04. Thanks @norru!
