### ISSUE TITLE
Typo: Direcotry -> Directory

### ISSUE THREAD

**Issue by crd477** [eclipse/corrosion#217]
https://github.com/eclipse/corrosion/blob/e31dababd08dd310fa888db968ade92ad636d9f5/org.eclipse.corrosion/src/org/eclipse/corrosion/messages.properties#L84

**Comment by mickaelistria** [comment]
Merged b715874 . Thanks a lot for the teport and the patch folks!

**Comment by mickaelistria** [comment]
Merged b715874 . Thanks a lot for the teport and the patch folks!
