### ISSUE TITLE
Make the Run/Debug action appear in Resource Perspective

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#220]
As Corrosion has good support for Run/Debug, it should enable related actions from the Resources perspective.

**Comment by mickaelistria** [comment]
cc @norru @serjiokov @akurtakov

**Comment by norru** [comment]
+1

**Comment by akurtakov** [comment]
If corrosion feature includes launchbar it automatically shows on every perspective. IMHO this is the easiest and best path forward.

**Comment by serjiokov** [comment]
> If corrosion feature includes launchbar it automatically shows on every perspective. IMHO this is the easiest and best path forward.

Yes @akurtakov it is the easiest way and best practice, enough to extend target file by corresponding items.

**Comment by serjiokov** [comment]
Suggest going this way.

**Comment by serjiokov** [comment]
So, working on including CDT launch bar to Resource perspective.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/corrosion/commit/8ca4d5115bf09b25b27524ad9dccd8707de0f5e8
