### ISSUE TITLE
Add Crate name to Rust main breakpoint

### ISSUE THREAD

**Issue by justdak** [eclipse/corrosion#221]
In many cases, it's useful to start the debugging process from the **main** function.

![image](https://user-images.githubusercontent.com/44570153/51382811-d2c0c000-1b28-11e9-923a-2631b67d7c41.png)

The problem is that the **main** function in Rust source file is not the same **main** that exists in the compiled binary. The Rust main should include the **crate** name.

![image](https://user-images.githubusercontent.com/44570153/51383118-9fcafc00-1b29-11e9-9882-3c86554b00d2.png)

So if the breakpoint value is **"new_rust_project::main"**, the gdb will stop right after the Rust main.

![image](https://user-images.githubusercontent.com/44570153/51383686-2e8c4880-1b2b-11e9-8df2-e617bcb00d51.png)

![image](https://user-images.githubusercontent.com/44570153/51383743-567bac00-1b2b-11e9-9b04-5251e90ff821.png)

I would like to discuss the idea to set **_crate_::main** breakpoint value by default when user select the Project in the Debug Configuration. If you accept this idea, I can provide the patch.

**Comment by mickaelistria** [comment]
Fixed with #224 . Thanks @justdak !
