### ISSUE TITLE
[Debug] Breakpoint missed

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#222]
I've installed last snapshot of Corrosion on top of Eclipse IDE 2019.03 M1.
If I add a breakpoint and run debug, the application doesn't stop and completes without hitting the breakpoint.

My test program is
```rust
fn main() {
	let n = 1;
	println!("Hello, world! {}", n);
}
```
and I've tried the breakpoint on all lines.

**Comment by justdak** [comment]
I have just downloaded Eclipse IDE 2019-03 M1 (4.11.0 M1)/Build id: 20190117-2133 on Windows and can't reproduce your issue about breakpoint missed. 
![image](https://user-images.githubusercontent.com/44570153/51404357-43390280-1b64-11e9-9d0b-01816a821590.png)

It is unlikely, but possible, that you built your application without debugging information (-g option). Could you please double check that you didn't use `cargo build --release`?

**Comment by mickaelistria** [comment]
Could not reproduce with 2019-03 M2 package.
