### ISSUE TITLE
No icons in Outline for 'struct' and 'type'

### ISSUE THREAD

**Issue by IMMZ** [eclipse/corrosion#225]
I see no icons (instead blank squares) for 'type' and 'struct' in Outline view.
Screenshot:
![_2019-01-22_16-12-55](https://user-images.githubusercontent.com/1856709/51538097-65cb6400-1e61-11e9-9151-cccc620423cb.png)

**Debian** 9.6, XFCE
**Corrosion**: Rust edition in Eclipse IDE	0.4.0.201901162320
**Eclipse IDE for Rust Developers**	4.10.0.20181214-0600

**Comment by mickaelistria** [comment]
This is an issue in TM4E that provides the outline and the icons.
Would you mind reporting it there https://bugs.eclipse.org/bugs/enter_bug.cgi?product=LSP4E&component=IDE ?

**Comment by norru** [comment]
Is the link correct? Points to LSP4E.

**Comment by IMMZ** [comment]
Reported there => https://bugs.eclipse.org/bugs/show_bug.cgi?id=543708
