### ISSUE TITLE
Random IDE freeze

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#232]
While browsing code between project and lib:

![selection_141](https://user-images.githubusercontent.com/889291/53362691-a4f24680-3932-11e9-9904-a3a486414f78.png)
[stuck_eclipse.jstack.txt](https://github.com/eclipse/corrosion/files/2902247/stuck_eclipse.jstack.txt)

No CPU used, IDE needs forced restart.

**Comment by mickaelistria** [comment]
Do you have the `.cargo` folder available as project in Eclipse workspace? Where is the lib file you're trying to open located?

**Comment by norru** [comment]
Yes, I do.

**Comment by norru** [comment]
https://github.com/eclipse/corrosion/issues/233

**Comment by norru** [comment]
Not seen in ages. Closing.
