### ISSUE TITLE
Use system installed Rust without rustup

### ISSUE THREAD

**Issue by Glandos** [eclipse/corrosion#235]
I am using Debian/testing, with Rust 1.32.0, which I guess is recent enough.

I don't want to install rustup. The installation method is scary, using `curl <random url> | sh` doesn't feel safe to me.

Is there a way to use corrosion without rustup?

By the way, I tried the [manual method](https://github.com/rust-lang/rustup.rs/#other-installation-methods), and here is the result:
```sh
> ./rustup-init 
error: it looks like you have an existing installation of Rust at:
error: /usr/bin
error: rustup cannot be installed alongside Rust. Please uninstall first
error: if this is what you want, restart the installation with `-y'
error: cannot install while Rust is installed
```

So I don't have any clue for now.

**Comment by mickaelistria** [comment]
Rustup is necessary to install RLS.
If you're scared by rustup you can simply audit the .sh file so you'll feel better, or just trust the fact that it's an official Rust project so you can trust this script as much as you trust installing the rust compiler.

In any case, it's not something that we can change in corrosion.

**Comment by norru** [comment]
`curl -o not_so_random.sh <random_url>`
`vim not_so_random.sh`

(thoroughly inspect the code to make sure there is no backdoor)

`chmod u+x not_so_random.sh`
`./not_so_random.sh`

;)

**Comment by norru** [comment]
Said that, I believe it is theoretically possible to install `rls` manually (or from source) but I have never done it and I expect to be a major pain in the neck.

**Comment by norru** [comment]
Also the `rust` toolchain usually installed as a distro package is quite out of date and even if it worked it would probably miss features which are fundamental to the Corrosion/RLS integration. Seen that before.

**Comment by Glandos** [comment]
https://packages.debian.org/search?keywords=rust-src&searchon=names&suite=all&section=all&sourceid=mozilla-search

Having a two month old release instead of the last release that is one month old is not that out of date.
As I understood, some other distributions reach the same goal: having an up-to-date rust. Because rust matters now.

I can edit and review one shell script. I can't do it for everything. [RVM](http://rvm.io/), [Pi-Hole](https://github.com/pi-hole/pi-hole/#one-step-automated-install), [Docker](https://get.docker.com/), and others. Moreover, the shell script in itself is safe. But it downloads a binary for my platform, and execute it, without checking anything but the X.509 certificate. So, yes, it's scary. A lot of thing can goes wrong with my current distribution package tool (`APT`), but a lot more can goes wrong with `curl | bash` method.

Installing `rls` manually seems possible, but the best way is to motivate someone to package it :)

**Comment by norru** [comment]
@Glandos 

> Having a two months old release instead of the last release that is one month old

In RLS/Corrosion terms, two months is "ancient" ;). In fact, it tends to target `nightly`. In the future, this is going to improve as the feature set stabilizes. Even if the RLS team have decided to change the version number with 1.x, this was a mistake in my opinion, as most features, as well as the interface itself, are, currently, quite in-flux.

I don't think it's even possible to build RLS with `stable`.

Said that I do understand your concern and your points are, in the general discourse, valid. Thing is, at the moment, my understanding is that what you are asking for is not even close to being a priority.
