### ISSUE TITLE
`Ctrl+C` often fails silently when editing during RLS builds.

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#236]
Ctrl+C has stopped working reliably in the last few weeks. This is very annoying, as `Ctrl+C` + `Ctrl+V` sometimes pastes old clipboard content.

Attempting to `Ctrl+C` + `Ctrl+V` multiple times eventually achieves the result.

I most cases I can observe RLS doing work in the background when this happens, which is "very often".

**Comment by norru** [comment]
I have seen this happening in Rust source (.rs) and Toml (.toml) files.

**Comment by mickaelistria** [comment]
Do you see some UI freeze as well? I think it's an issue that's already reported to LSP4J cascading the Ctrl key causing a small UI Freeze and then further keystrokes being ignored.

**Comment by norru** [comment]
Yes, I can see a very short UI freeze.

**Comment by mickaelistria** [comment]
Ok, so I think it's a consequence of https://github.com/eclipse/lsp4j/issues/308

**Comment by norru** [comment]
Looks like they kinda fixed it 6 days ago, perhaps the LSP4J dep hasn't filtered through yet?

**Comment by mickaelistria** [comment]
The fixed version isn't released yet, and since we were on track for the 2019-03 release, we were in a freeze and couldn't depend on non-released version.
We'll update the dependencies soon and hopefully this would get fixed without additional effort.

**Comment by norru** [comment]
Oh, I see. I'll bite the bullet for a bit longer.

**Comment by mickaelistria** [comment]
You can install a 0.7.1 (or even a 0.8.0) build of LSP4J and hopefully see this fixed (and no additional bug introduced). I don't have the p2 repo URLs beforehand.

**Comment by norru** [comment]
I haven't found 0.7.1, but 0.8.0 was available from Nightly. Scary.

**Comment by norru** [comment]
I'm now on 2019-03 and haven't seen this for a while. Cautiously closing.
