### ISSUE TITLE
RLS update breaks formatting

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#241]
I think the latest RLS implements formatting in a different way. As a result `Ctrl+Shift+F` produces no effect.

How to reproduce:

- update to RLS from nightly-2019-04-11
- edit any valid .rs file and artificially alter the indentation
- attempt autoformat using `Ctrl+Shift+F`
- result: no changes
- expected result: text is indented correctly

Additional information:
There is no error message in the RLS logs. It does appear that the format operation is returning just a list of changes lines rather than the whole formatted file.

```
[t=1554978597331] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"56","method":"textDocument/formatting","params":{"textDocument":{"uri":"file:[...]"},"options":{"tabSize":4,"insertSpaces":false}}}
[t=1554978597359] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","id":"56","result":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":18446744073709551615}},"newText":"use gtk::traits::*;"}]}
```

**Comment by norru** [comment]
Workaround: do not update RLS.

**Comment by norru** [comment]
This is how the old RLS replies to a formatting request:

```
[t=1554979024845] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"20","method":"textDocument/formatting","params":{"textDocument":{"uri":"file:[...].
rs"},"options":{"tabSize":4,"insertSpaces":false}}}
[t=1554979024876] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","id":"20","result":[{"range":{"start":{"line":0,"character":0},"end":{"line":1274,"character":0}},"newText":"[content of the whole file"
...
```

**Comment by mickaelistria** [comment]
`"character":18446744073709551615` is definitely an erroneous value (character is supposed to be the "column" of the character. The bug is in RLS ;)

**Comment by norru** [comment]
Good spot, I would have guessed the same if I had seen it :D

**Comment by norru** [comment]
https://github.com/rust-lang/rls/pull/1422

It appears that the big number was code for "to the end of the line".

**Comment by norru** [comment]
fixed with RLS in `nightly-2019-04-14`
