### ISSUE TITLE
Opening a `.cargo` file causes the IDE to become unstable

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#242]
If I open and browse a file in `.cargo` by `Ctrl+click` on a library symbol, the IDE becomes unstable. Also, navigating symbols in that file produces no effect.

"Unstable" could mean one or more of:

- no response (IDE frozen)
- builds constantly retriggered
- symbol lookup failed
- one or more of "could not find `Cargo.toml` in `/` or any parent directory" popups

I have had a look at the LSP4E logs but there is nothing nasty there. The last response before instability is `didOpen` (referred to the `.cargo` library source file).

Related to https://github.com/rust-lang/rls/issues/1431

While the problem may well be RLS, Corrosion has no control over the stability of RLS itself but it's not acceptable to say "it's RLS's fault" and end up with no editing capabilities.

RLS handling needs to be more robust - not sure how to behave in those cases, perhaps have Eclipse kill stalled RLS after some "hard" timeout?

**Comment by norru** [comment]
Workaround:

- place a `Cargo.toml` file containing an empty `[workspace]` section in `.cargo`
- place an empty `Cargo.toml` in `$HOME`

**Comment by mickaelistria** [comment]
Does you recent change in LSP4E improve that?

**Comment by norru** [comment]
Seems better with the last LSP4E (2019-08-12)

**Comment by jiapei100** [comment]
> 

```console
➜  .cargo cargo update
error: you can't generate a lockfile for an empty workspace.
```
