### ISSUE TITLE
Renaming from Quick fix suggestion breaks the code.

### ISSUE THREAD

**Issue by IMMZ** [eclipse/corrosion#247]
### Steps to reproduce.
1. Write some code with invalid case somethingLikeThis. Make this name appear more than once on the block of code.
2. Put mouse pointer on this name. Eclipse will suggest you to fix it:
![before](https://user-images.githubusercontent.com/1856709/56459586-48ddf880-639e-11e9-9a22-4ee8feb988e2.png)
3. Agree by clicking on the link. Eclipse will rename only one occurrence of the name, the rest ones are now invalid.
 ![after](https://user-images.githubusercontent.com/1856709/56459581-44b1db00-639e-11e9-945a-1d7c78863061.png)

### Small improvement suggestion for renaming.
It would be nice when you choose Refactor - Rename to see the current name in the edit line not the _newName_. It could be annoying when you want to fix only one character because of some typo. It leads you to retyping the whole word again.
![rename](https://user-images.githubusercontent.com/1856709/56459587-48ddf880-639e-11e9-9397-9a5f349f53cf.png)

### Additional info.
Eclipse IDE for Rust Developers
Version: 2018-12 (4.10.0)
Build id: 20181214-0600
OS: Linux, v.4.9.0-8-amd64, x86_64 / gtk 3.22.11, WebKit 2.18.6
Java version: 1.8.0_212
Corrosion: Rust edition in Eclipse IDE: 0.4.1.201903251734
Language Server Protocol client for Eclipse IDE (Incubation): 0.9.1.201904031126

[org.eclipse.corrosion.rls.log](https://github.com/eclipse/corrosion/files/3118562/org.eclipse.corrosion.rls.log)

**Comment by norru** [comment]
https://github.com/eclipse/corrosion/issues/187

**Comment by norru** [comment]
It might be an RLS bug.

**Comment by mickaelistria** [comment]
For the bug, it would be great if you can enable log to file for RLS (Window > Preference > Language Servers > Logs) and then share the log files you'd get in `<workspace>/languageServers-log`. With this, we can immediately identify whether LSP4E or RLS is to blame here.

For the suggestion, it's a corollary of https://bugs.eclipse.org/bugs/show_bug.cgi?id=541855

**Comment by IMMZ** [comment]
Added rls log after quick fix renaming (see issues info above). Noticed if I rename it using Refactor menu F2 the code is renamed well - the issue only applies on quick fix. Also F2 doesn't work on my Debian, I need to use mouse and context menu to rename something.

**Comment by norru** [comment]
F2 also broken for me (Ubuntu, Devuan)

https://github.com/eclipse/corrosion/issues/215#issuecomment-453756011

**Comment by akurtakov** [comment]
Closing due to lack of interest from reporter.
