### ISSUE TITLE
Contributing: javax.xml.stream and javax.xml.bind dependencies

### ISSUE THREAD

**Issue by dc740** [eclipse/corrosion#248]
I tried to follow the CONTRIBUTING.md file, but I keep getting an error stating this when I try to run it from Eclipse:
`Missing Constraint: Import-Package: javax.xml.bind; version="0.0.0"`

If I hit continue the new eclipse instance starts BUT there are no references to Rust. It looks like the plugin was not included at all in then run.

This is for the eclipse.cdt.core plugin. Is this bug part of Eclipse, or Corrosion?

I understand JAXB is deprecated and completely removed, but I don't fully understand where is the dependency. 

I'm using java 11, since newer Ubuntu versions only come with java >11. Java 8 or 9 are not even an option. 

I'm also using the latest Eclipse for Eclipse Commiters package (downloaded today) and the latest corrosion code, also cloned today.

I tried to use maven dependency tree to see where it came from, but I get this error when I try to run it
`[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.eclipse.corrosion.tests: Could not resolve dependencies for project org.eclipse.corrosion:org.eclipse.corrosion.tests:eclipse-test-plugin:0.4.0-SNAPSHOT: Could not find artifact org.eclipse.corrosion:org.eclipse.corrosion:jar:0.4.1-SNAPSHOT -> [Help 1]                                                                                
[ERROR]`

**Comment by dc740** [comment]
Update:
It's a requirement to actually import the projects as Maven projects, or the "Run As... Eclipse application" won't include Rust by default. Originally I simply tried to import an existing project.

I don't know where the error about javax.xml.* comes from, but at least I can ignore it for now, since Corrosion is actually displayed in the new run configuration I did after re-importing the project. 

Feel free to close this if this error (javax.xml.stream missing) cannot be avoided from Corrosion. I would have fixed it myself but I couldn't determine the cause.

**Comment by mickaelistria** [comment]
Hi,
Sorry, I've forgotten about this. Did you manage to make any progress on that matter?

**Comment by dc740** [comment]
No problem. I didn't fix the error at all. I managed to make the project work by importing it as a maven project and didn't spend more time on the other errors.

**Comment by akurtakov** [comment]
I'm closing this one now. Please open a new one or even better PR for any fix that is still needed.
