### ISSUE TITLE
Can't update Eclipse Corrosion.

### ISSUE THREAD

**Issue by IMMZ** [eclipse/corrosion#251]
When I try update the IDE via 'Check for updates' I get error 'No remedy found'.

Raw Log:

> !ENTRY org.eclipse.equinox.p2.operations 4 0 2019-06-12 09:49:23.611
> !MESSAGE No remedy found
> 
> !ENTRY org.eclipse.equinox.p2.operations 4 10053 2019-06-12 09:49:24.060
> !MESSAGE Operation details
> !SUBENTRY 1 org.eclipse.equinox.p2.director 4 10053 2019-06-12 09:49:24.061
> !MESSAGE Cannot complete the install because one or more required items could not be found.
> !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-06-12 09:49:24.061
> !MESSAGE Software being installed: Language Server Protocol client for Eclipse IDE (Incubation) 0.10.0.201906060902 (org.eclipse.lsp4e 0.10.0.201906060902)
> !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-06-12 09:49:24.061
> !MESSAGE Missing requirement: Language Server Protocol client for Eclipse IDE (Incubation) 0.10.0.201906060902 (org.eclipse.lsp4e 0.10.0.201906060902) requires 'osgi.bundle; org.eclipse.ui.workbench 3.115.0' but it could not be found
> 
> !ENTRY org.eclipse.equinox.p2.operations 4 10053 2019-06-12 09:49:24.109
> !MESSAGE Operation details
> !SUBENTRY 1 org.eclipse.equinox.p2.director 4 10053 2019-06-12 09:49:24.109
> !MESSAGE Cannot complete the install because one or more required items could not be found.
> !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-06-12 09:49:24.109
> !MESSAGE Software being installed: Language Server Protocol client for Eclipse IDE (Incubation) 0.10.0.201906060902 (org.eclipse.lsp4e 0.10.0.201906060902)
> !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-06-12 09:49:24.109
> !MESSAGE Missing requirement: Language Server Protocol client for Eclipse IDE (Incubation) 0.10.0.201906060902 (org.eclipse.lsp4e 0.10.0.201906060902) requires 'osgi.bundle; org.eclipse.ui.workbench 3.115.0' but it could not be found
> 
> !ENTRY org.eclipse.equinox.p2.operations 4 10053 2019-06-12 09:49:26.654
> !MESSAGE Operation details
> !SUBENTRY 1 org.eclipse.equinox.p2.director 4 10053 2019-06-12 09:49:26.654
> !MESSAGE Cannot complete the install because one or more required items could not be found.
> !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-06-12 09:49:26.654
> !MESSAGE Software being installed: Language Server Protocol client for Eclipse IDE (Incubation) 0.10.0.201906060902 (org.eclipse.lsp4e 0.10.0.201906060902)
> !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-06-12 09:49:26.654
> !MESSAGE Missing requirement: Language Server Protocol client for Eclipse IDE (Incubation) 0.10.0.201906060902 (org.eclipse.lsp4e 0.10.0.201906060902) requires 'osgi.bundle; org.eclipse.ui.workbench 3.115.0' but it could not be found
> 
> !ENTRY org.eclipse.equinox.p2.operations 4 10053 2019-06-12 09:49:26.657
> !MESSAGE Operation details
> !SUBENTRY 1 org.eclipse.equinox.p2.director 4 10053 2019-06-12 09:49:26.657
> !MESSAGE Cannot complete the install because one or more required items could not be found.
> !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-06-12 09:49:26.657
> !MESSAGE Software being installed: Language Server Protocol client for Eclipse IDE (Incubation) 0.10.0.201906060902 (org.eclipse.lsp4e 0.10.0.201906060902)
> !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-06-12 09:49:26.657
> !MESSAGE Missing requirement: Language Server Protocol client for Eclipse IDE (Incubation) 0.10.0.201906060902 (org.eclipse.lsp4e 0.10.0.201906060902) requires 'osgi.bundle; org.eclipse.ui.workbench 3.115.0' but it could not be found

Any ideas how to fix it? Some time before it is updated well. No changes in settings were made from that time.

**Comment by norru** [comment]
Latest versions of Corrosion require Eclipse 2019-06 (currently in RCx)

**Comment by mickaelistria** [comment]
Release of 2019-06 is next week.
To try a RCx, there are several possibilities:
* Get the full package from https://www.eclipse.org/downloads/index-developer.php
* Upgrade you current IDE with the same approach as described in https://wiki.eclipse.org/FAQ_How_do_I_upgrade_Eclipse_IDE%3F#Upgrading_existing_Eclipse_IDE_and_Installed_Features_to_newer_release , using https://download.eclipse.org/releases/2019-06/ as repository (it currently contains the milestones and RCs and will contain the release next week).
