### ISSUE TITLE
Missing integration of rustfmt

### ISSUE THREAD

**Issue by ctron** [eclipse/corrosion#252]
To me it looks like currently there is no way to automatically or semi-automatically do source code formatting with `rustfmt`.

* My preferred choice would be to run be able to configure `rustfmt` as a "Save action"
* At least I would like to be able to press `Ctrl+Shift+F` (like for Java) and get the code formatted

**Comment by mickaelistria** [comment]
`rustfmt` integration is provided by RLS. `Ctrl+Shift+F` is supposed to be bound to LSP format operation, and it was reported as working in some other tickets. You can also access it from context menu.
About save action, it's something that should probably be requested to RLS or even LSP. I think it's beyond the scope of Corrosion.
However, on possible workaround is to make invocation of `rustfmt` an external build step in the project. From project settings, you can add some external builder.

**Comment by mickaelistria** [comment]
On 2nd thoughts, I think it could be a feature in LSP4E.

**Comment by ctron** [comment]
At least for me, manually triggering the code formatting doesn't work.

**Comment by mickaelistria** [comment]
Ok.
Would you be able to check the version/build date of RLS you're using?

**Comment by ctron** [comment]
`rls 1.35.0 (49efc06 2019-04-06)`

**Comment by norru** [comment]
> integration is provided by RLS. Ctrl+Shift+F is supposed to be bound to LSP format 

At the moment `Ctrl+Shift+F` is unusable for large files as it knackers the syntax highlighting. Am I the only one seeing this issue (on 3x Linux machines though)?

Having a `rustfmt` way out which doesn't require `cargo fmt` in a terminal would be great.

**Comment by mickaelistria** [comment]
Can you please share such a non-formatted large file that seems to always reproduce the issue for you?

**Comment by ctron** [comment]
For me that issue is always the case. Independent of the size of the file.

**Comment by norru** [comment]
> Can you please share such a non-formatted large file that seems to always reproduce the issue for you?

It's not project dependent. Every Cargo project I import from GitHub would do. However, here's a link to a random one in which I have just reproduced on:

https://github.com/itadinanta/gfx-gtk/blob/master/src/lib.rs

Funny thing, while I was trying this I actually managed to reproduce @ctor's issue where 'Ctrl+Shift+F` doesn't have any effect at all, in another project. It does look like it's an RLS issue though, as both `cargo build` and `cargo fmt` complete successfully.

```
[t=1562068879078] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"6","method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///[..]/3rdParty/ofx-rs/ofx/src/handle.rs"},"options":{"tabSize":4,"insertSpaces":false}}}
[t=1562068879079] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Reformat failed to complete successfully"},"id":"6"}
```

I wonder, are most of Corrosion's users building "Hello World" projects, or perhaps my projects are cursed? ;)

**Comment by mickaelistria** [comment]
> I wonder, are most of Corrosion's users building "Hello World" projects,

To be honest, I have the impression you're currently "most of Corrosion's users". Maybe other users face the issue and don't care reporting...

**Comment by ctron** [comment]
Ok, checking the logs shows:

~~~
[t=1562070660321] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"11","method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///home/jreimann/Development/workspace-esp32-rust/rust-esp32-hono/src/main.rs"},"options":{"tabSize":4,"insertSpaces":false}}}
[t=1562070660322] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Reformat failed to complete successfully"},"id":"11"}

~~~

**Comment by norru** [comment]
@ctor, if you think this is issued in error, could you please file a bug to https://github.com/rust-lang/rls/issues? There is a suspiciously similar one that I've filed months ago: https://github.com/rust-lang/rls/issues/1397

We can probably wait to close this at least until after the RLS crew gives this one some eyeballs.

**Comment by norru** [comment]
Also: @ctor does the situation improve after a `cargo clean`?

**Comment by ctron** [comment]
Still I see one enhancement/fix here. If the RLS reports and error like that, that should pop up in the Eclipse error log.

**Comment by norru** [comment]
Also https://github.com/rust-lang/rls-vscode/issues/534

**Comment by ctron** [comment]
Just checked this with Rust 1.38 and Eclipse 2019-09 and it works.

**Comment by ctron** [comment]
From my point of view, this can be closed.
