### ISSUE TITLE
Contributing: Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#253]
I have been trying to load the Plugin source in a fresh install of Eclipse 2019-06 for Committers or Eclipse 2019-03 for Committers, following the usual steps as for the contibutors guide.

The project build within Eclipse seems to fail with the following error (multiple instances in `org.eclipse.corrosion` and `org.eclipse.corrosion.tests`). 
```
Plugin execution not covered by lifecycle configuration: org.eclipse.tycho:tycho-compiler-plugin:1.4.0:compile (execution: default-compile, phase: compile)
```

**Comment by norru** [comment]
Trying to break it down now. I managed to do a `mvn install` of `target-platform` and now the error I get is the following:

```
[INFO] Scanning for projects...
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[INFO] Computing target platform for MavenProject: org.eclipse.corrosion:org.eclipse.corrosion:0.4.1-SNAPSHOT @ /u01/home/nico/Projects/itadinanta/corrosion/org.eclipse.corrosion/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.11/
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.11/
[INFO] Adding repository http://download.eclipse.org/eclipse/updates/4.11
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.11/R-4.11-201903070500/
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.11/R-4.11-201903070500/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2019-03/
[INFO] Adding repository http://download.eclipse.org/releases/2019-03
[INFO] Fetching p2.index from https://download.eclipse.org/technology/epp/packages/2019-03/
[INFO] Fetching p2.index from https://download.eclipse.org/technology/epp/packages/2019-03/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2019-03/201903201000/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2019-03/201903201000/
[INFO] Fetching p2.index from http://download.eclipse.org/cbi/updates/license/
[INFO] Fetching p2.index from http://download.eclipse.org/cbi/updates/license/
[INFO] Adding repository http://download.eclipse.org/cbi/updates/license
[INFO] Fetching p2.index from http://download.eclipse.org/cbi/updates/license/2.0.0.v20180130-0820/
[INFO] Fetching p2.index from http://download.eclipse.org/cbi/updates/license/2.0.0.v20180130-0820/
[INFO] Fetching p2.index from http://download.eclipse.org/cbi/updates/license/2.0.1.v20180423-1114/
[INFO] Fetching p2.index from http://download.eclipse.org/cbi/updates/license/2.0.1.v20180423-1114/
[INFO] Resolving dependencies of MavenProject: org.eclipse.corrosion:org.eclipse.corrosion:0.4.1-SNAPSHOT @ /u01/home/nico/Projects/itadinanta/corrosion/org.eclipse.corrosion/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.corrosion:org.eclipse.corrosion:0.4.1-SNAPSHOT @ /u01/home/nico/Projects/itadinanta/corrosion/org.eclipse.corrosion/pom.xml
[INFO] 
[INFO] ------------< org.eclipse.corrosion:org.eclipse.corrosion >-------------
[INFO] Building org.eclipse.corrosion 0.4.1-SNAPSHOT
[INFO] ---------------------------[ eclipse-plugin ]---------------------------
[INFO] 
[INFO] --- tycho-packaging-plugin:1.4.0:build-qualifier (default-build-qualifier) @ org.eclipse.corrosion ---
[INFO] The project's OSGi version is 0.4.1.201903251734
[INFO] 
[INFO] --- tycho-packaging-plugin:1.4.0:validate-id (default-validate-id) @ org.eclipse.corrosion ---
[INFO] 
[INFO] --- tycho-packaging-plugin:1.4.0:validate-version (default-validate-version) @ org.eclipse.corrosion ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.3:prepare-agent (default) @ org.eclipse.corrosion ---
[INFO] argLine set to -javaagent:/home/nico/.m2/repository/org/jacoco/org.jacoco.agent/0.8.3/org.jacoco.agent-0.8.3-runtime.jar=destfile=/u01/home/nico/Projects/itadinanta/corrosion/org.eclipse.corrosion/target/jacoco.exec,append=true,includes=org.eclipse.corrosion*
[INFO] 
[INFO] --- download-maven-plugin:1.4.1:wget (fetch-rustup-install-script) @ org.eclipse.corrosion ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.337 s
[INFO] Finished at: 2019-06-23T13:37:08+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget (fetch-rustup-install-script) on project org.eclipse.corrosion: Execution fetch-rustup-install-script of goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget failed: java.lang.ClassNotFoundException: com.googlecode.download.maven.plugin.internal.CachedFileEntry -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by mickaelistria** [comment]
> Plugin execution not covered by lifecycle configuration: org.eclipse.tycho:tycho-compiler-plugin:1.4.0:compile (execution: default-compile, phase: compile)

m2e should show a quickfix on those errors, like "Search for connectors" or something like that. By going through this process, you should be guided to installation of the m2e-tycho connector that would fix such issues.
However, m2e-tycho doesn't do much important things for LSP4E, so you may also just follow the quickfix that allows to skip this execution.
Anyway, I think Tycho itself could improve that, I've opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=548569

> [ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget (fetch-rustup-install-script) on project org.eclipse.corrosion: Execution fetch-rustup-install-script of goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget failed: java.lang.ClassNotFoundException: com.googlecode.download.maven.plugin.internal.CachedFileEntry -> [Help 1]

This one is nasty and is a bug in download-maven-plugin not properly handling version change because it reuses the cache in a former version and isn't able to process it.
To work around it, delete your `.m2/repository/.cache/download-maven-plugin` folder and retry a build.

**Comment by norru** [comment]
I have tried your suggested workaround. After installing the missing components, `org.eclipse.corrosion.tests` has no errors.

`org.eclipse.corrosion` still fails with

```
CoreException: Could not get the value for parameter compilerId for plugin execution default-compile: PluginResolutionException: Plugin org.eclipse.tycho:tycho-compiler-plugin:1.4.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-compiler-plugin:jar:1.4.0 -> org.eclipse.tycho:tycho-compiler-jdt:jar:1.4.0: ArtifactDescriptorException: Failed to read artifact descriptor for org.eclipse.tycho:tycho-compiler-jdt:jar:1.4.0: ArtifactResolutionException: Failure to transfer org.eclipse.tycho:tycho-compiler-jdt:pom:1.4.0 from https://repo.eclipse.org/content/groups/cbi was cached in the local repository, resolution will not be reattempted until the update interval of cbi has elapsed or updates are forced. Original error: Could not transfer artifact org.eclipse.tycho:tycho-compiler-jdt:pom:1.4.0 from/to cbi (https://repo.eclipse.org/content/groups/cbi): repo.eclipse.org
```

I'll try and see what happens deleting the cache

**Comment by norru** [comment]
Deleting the cache, doing a mvn update with -U and also attempting full builds a few times, seem to have fixed the problem in the IDE but `mvn clean verify -U -DskipTests` still produces the following error:

```
[ERROR] Baseline and reactor have same fully qualified version, but with different content
Baseline /home/nico/.m2/repository/p2/osgi/bundle/org.eclipse.corrosion/0.4.1.201903251734/org.eclipse.corrosion-0.4.1.201903251734.jar and reactor /u01/home/nico/Projects/itadinanta/corrosion/org.eclipse.corrosion/target/org.eclipse.corrosion-0.4.1-SNAPSHOT.jar are made of different bytes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] parent 0.4.1-SNAPSHOT .............................. SUCCESS [  0.299 s]
[INFO] target-platform 0.4.1-SNAPSHOT ..................... SUCCESS [  0.200 s]
[INFO] org.eclipse.corrosion 0.4.1-SNAPSHOT ............... FAILURE [  6.809 s]
[INFO] org.eclipse.corrosion.tests 0.4.0-SNAPSHOT ......... SKIPPED
[INFO] org.eclipse.corrosion.feature 0.4.1-SNAPSHOT ....... SKIPPED
[INFO] repository 0.4.1-SNAPSHOT .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43.866 s
[INFO] Finished at: 2019-06-24T22:36:30+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:1.4.0:compare-version-with-baselines (compare-version-with-baseline) on project org.eclipse.corrosion: Baseline and reactor have same fully qualified version, but with different content
[ERROR] Baseline /home/nico/.m2/repository/p2/osgi/bundle/org.eclipse.corrosion/0.4.1.201903251734/org.eclipse.corrosion-0.4.1.201903251734.jar and reactor /u01/home/nico/Projects/itadinanta/corrosion/org.eclipse.corrosion/target/org.eclipse.corrosion-0.4.1-SNAPSHOT.jar are made of different bytes
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.eclipse.corrosion
```

**Comment by mickaelistria** [comment]
Please pull latest commit that should get rid of this error.
However, you may still see this message in the future: the build has some checks to ensure we properly bump version when there is a change (we typically avoid bumping versions when there is no change), so if you've made a change and then see it, it means you need to increase version in pom.xml and MANIFEST.MF

**Comment by norru** [comment]
Pulling latest commit did not fix the error, however I managed to push through by changing all instances of `4.x.0.qualifier` and `4.x.0-SNAPSHOT` to `4.2.`

Thanks for the assistance. I feel like there is still quite a lot of friction that may prevent contributors from joining in, though.

**Comment by mickaelistria** [comment]
> Pulling latest commit did not fix the error, however I managed to push through by manually changing all instances of 4.x.0.qualifier and 4.x.0-SNAPSHOT to 4.2.

Did you make modifications on the code or is it the same HEAD as master?
In case you made the modification, the error message is desired: it tells that since 4.1.0 was already released and you've made modification, you have to increase the version (we don't allow to build a version that was already released).

**Comment by norru** [comment]
As far as I saw it, I merged my changes in but didn't change the code. There were a few changes to Eclipse's settings files, which AFAIK are not part of the build.

I cannot exclude I missed something though. Anyway, the error is good, what should happen in these cases is that as soon as a version is released, the POMs versions should be incremented so it's not up to each contributor do do it over and over again.

**Comment by mickaelistria** [comment]
> There were a few changes to Eclipse's settings files, which AFAIK are not
part of the build.

That could very well be it. By default, the .settings are not excluded from
version computation and check.

**Comment by mickaelistria** [comment]
With https://github.com/eclipse/corrosion/commit/102d849542dc93df94799b7d789e403b12eb8559 , changing .settings shouldn't require bumping the version as long as the change in .settings/ doesn't result in different binary content.

**Comment by norru** [comment]
Fair enough :). Releases should trigger version number increments as good practice though ;)

**Comment by mickaelistria** [comment]
>  Releases should trigger version number increments as good practice though ;)

Actually, in modular/composite projects, it's not a best practice to increment version of some artifacts as long as no change was actually made. The approach of letting version and artifact remain identical as long as there is no change is the real best practice, it's just not the most common one as it's harder to implement than making version increase an automated post-release step.

**Comment by norru** [comment]
>  it's just not the most common one

I can see why.
