### ISSUE TITLE
Marker Tooltips convert `&` into underline

### ISSUE THREAD

**Issue by ctron** [eclipse/corrosion#254]
To me it looks like the tooltips shown by Corrosion do translate a `&` from a message into an underline style:

![image](https://user-images.githubusercontent.com/202474/59978325-8a2b9800-95db-11e9-8620-ee4725f3407b.png)
![image](https://user-images.githubusercontent.com/202474/59978328-8d268880-95db-11e9-9c4f-9394ac107c0c.png)

**Comment by mickaelistria** [comment]
Reported upstream as https://bugs.eclipse.org/bugs/show_bug.cgi?id=548679

**Comment by mickaelistria** [comment]
This can be fixed by using latest build of LSP4E: http://download.eclipse.org/lsp4e/snapshots/
Just updating TP and rebuild would fix it in Corrosion. Let's keep the ticket open until we have verified it's fixed in Corrosion.
