### ISSUE TITLE
Question: How to set a default Run configuration

### ISSUE THREAD

**Issue by kterhorst** [eclipse/corrosion#271]
Hello, this is a pretty basic question and I am sorry if I waste your time. Everytime I click the Run button a dialog "Select a way to run <filename>: Cargo Based Rust Project; Cargo Based Rust Test" appears. Is there a way to set a default configuration that prevents this dialog from showing up? I know that one can click on the small arrow next to the run button and select the configuration. However, I would like to run the application by clicking just once ;) If this isn't possible I would suggest adding that.

**Comment by norru** [comment]
Hi @kterhorst, you can create a run configuration as a "template" and then **duplicate** it. Would that work?
