### ISSUE TITLE
Undo rename breaks problem markers

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#276]
How to reproduce:

- rename a symbol "A" which appears in multiple modules, such as a function name to "B"
- undo rename (reply yes to prompt when asked if you want to undo on all files) so all references to "B" switch back to "A"
- error markers appear that reference "B" even if "B" has been replaced by "A"
- markers will persist after edits, restart of the IDE is required to trigger a rebuilt

**Comment by mickaelistria** [comment]
It could be an issue with RLS doesn't receive notifications about changes in other files, or it receives the changes but doesn't care.

**Comment by mickaelistria** [comment]
Corrosion moved to rust-analyzer in the meantime; can you please try latest release or snapshot and verify whether issue is still present?

**Comment by akurtakov** [comment]
No reply thus closing. Please reopen if you still face the issue.
