### ISSUE TITLE
Information links not clickable

### ISSUE THREAD

**Issue by ctron** [eclipse/corrosion#277]
Every now and then the Rust LS offers you more information by giving you a URL. However, those URLs are neither clickable, nor copyable.

![image](https://user-images.githubusercontent.com/202474/66701153-6bbbea80-ecf9-11e9-8a16-50c7ab5f1004.png)

**Comment by Boereck** [comment]
I created an issue for LSP4E: https://bugs.eclipse.org/bugs/show_bug.cgi?id=558573
I also found a solution, the question is now if the conversion should be the default behavior.

**Comment by Boereck** [comment]
Just as an FYI: The issue moved even more upstream to the Eclipse Mylyn project:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=559037

**Comment by akurtakov** [comment]
Links are clickable with master.
