### ISSUE TITLE
Running a single test

### ISSUE THREAD

**Issue by growingspaghetti** [eclipse/corrosion#278]
![Selection_014](https://user-images.githubusercontent.com/19510322/67145598-64618780-f28b-11e9-80d7-9c0dc95f98d2.png)
Like Visual Studio Code, I would like to run a single test. 
![Selection_015](https://user-images.githubusercontent.com/19510322/67145599-64618780-f28b-11e9-8ae6-25ca9006213c.png)
Sadly, I don't know how to add that feature by myself.

**Comment by Boereck** [comment]
Yeah, I wanted to implement that feature like a year ago. Unfortunately, a combination of lack of documentation of RLS, my lack of knowledge how LSP4E is working (which Corrosion is based on) and my general lack of time did not make it happen so far. This is still one of the features I want to use myself, so it is (still) on the back burner.

**Comment by mickaelistria** [comment]
Running tests is not in the scope of LSP4E.
It could be if we were using a debug adapter to launch/debug rust apps, we Corrosion relies on the good old CDT GDB interface (that's quite good). But if you don't need debug, it doesn't change much.
I think all this story is mostly a matter of creating a new Launch Configuration type for test executions, with related configuration pages and launch shortcuts.

**Comment by Boereck** [comment]
I found the way to enable the CodeMining in Eclipse, by enabling the respective CodeLens on the RLS. Unfortunately the LSP4E Plugin does not seem to allow to act on click on CodeMinings to handle the Command sent by the CodeLens response. I created a bug entry for LSP4E upstream: https://bugs.eclipse.org/bugs/show_bug.cgi?id=553565
When this is implemented, running a single test via CodeMining is possible to be implemented. Details if it makes sense to create a Run Configuration (and which type) on click still has to be figured out.

**Comment by Boereck** [comment]
Status update: The upstream issue is solved. Implementation seems feature complete, but lacks some unit tests.

Details:

- A click on "Run test" will check, if a Launch Configuration with all needed parameters exists
- If not, the Launch Configuration a temporary launch Configuration will be created
- The existing or new Launch Configuration will be started

If no Launch Configuration exists, the created Launch Configuration will not be persisted. In my experience I click on so many of those, that the list of Launch Configurations gets cluttered very fast. Maybe in future we can somehow allow persisting the configuration (maybe holding a key while clicking on the CodeMining or something).

**Comment by mickaelistria** [comment]
@Boereck Great changes! What's your tentative schedule to deliver the change in a Corrosion release? If we rush, we can try it for 4.14...

**Comment by Boereck** [comment]
@mickaelistria I think I can get it done in one or two days. Is it possible to squeeze in for 4.14? I think officially, the deadline for feature freeze just ended.

**Comment by mickaelistria** [comment]
Corrosion is an incubating project and no other proejct depends on it, so it's not that bad if we just add a feature in RC2.
That said, if you prefer not rushing and take more time, it's also OK. Users should get update of Corrosion automatically anyway, so if we release a bit later, it wouldn't take long before most users take advantage of the new release (they get 1 notification per week if there is an update)

**Comment by Boereck** [comment]
Well, let's see then if I can get enough tests (both automated and manual) done before Friday to get enough confidence. If so, I'd give it a green light, otherwise we'll postpone the feature.
