### ISSUE TITLE
Update rustup script shipped with corrosion

### ISSUE THREAD

**Issue by Boereck** [eclipse/corrosion#280]
I want to update the `rustup-init.sh` script, which is currently shipped with corrosion, with the most recent release, which can be found [here](https://raw.githubusercontent.com/rust-lang/rustup.rs/1.20.2/rustup-init.sh). Besides being up to date, this update allows us to install the RLS together with rustup. This spares the user one additional step.

# Open Questions
Do we have to create an IP CQ for the update? The new version also does not contain a license header (even though the license did not change: Apache/MIT dual licensed). Do we have to alter the script, or can we add a text file which declares the license of the script?

**Comment by mickaelistria** [comment]
> Do we have to create an IP CQ for the update? 

Yes, I think so.

>  The new version also does not contain a license header 

I think it's OK if there is a license information in the Git repo hosting it.

**Comment by mickaelistria** [comment]
Can you open the CQ?

**Comment by Boereck** [comment]
I tried to start one, not sure if I chose the right option during creation. Anyway, the CQ can be found here:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21017
