### ISSUE TITLE
Pasting into rs file UTF-8 characters sometimes breaks syntax highlight.

### ISSUE THREAD

**Issue by cristianprice** [eclipse/corrosion#284]
Hi guys,
First of all thank you for the amazing work. Second the dirty complain: sometimes when I paste text from utf-8 sources like pdf books, it messes up the text highlight. I think this is related to white space utf-8 characters because I cant find anything unusual in the code. I use Manjaro 64bits and okular for the book I am reading on rust. Whenever I paste code the text becomes plain text in certain parts of the file. If I delete some of the white spaces here and there the highlight comes back. 
Thanks,
C

**Comment by akurtakov** [comment]
Do you still face the issue with latest version?

**Comment by akurtakov** [comment]
Closing due to lack of interest.
