### ISSUE TITLE
Update Eclipse Marketplace Entry and Formalities

### ISSUE THREAD

**Issue by Boereck** [eclipse/corrosion#308]
The [Eclipse Marketplace entry](https://marketplace.eclipse.org/content/eclipse-corrosion-rust-edition-and-debug) for Corrosion lists at least one link to the Corrosion fork of @LucasBullen . @mickaelistria do you know if we can access and change the Marketplace entry? If not, can we write an admin to get access?

Related to this: @LucasBullen is still listed as project lead on the [project page](https://projects.eclipse.org/projects/tools.corrosion/who), and @mickaelistria is not, even though he was clearly [elected](https://projects.eclipse.org/projects/tools.corrosion/elections/election-mickael-istria-away-until-july-30th-project-lead-eclipse-corrosion-eclipse-ide-rust). This raises some questions for me:

- What is the process for retiring an inactive project lead? I see, that I have the option to revoke Lukas' Lead status, but it feels hostile to do this without consulting him somehow. However, in the past he did not respond to questions regarding Corrosion.
- Do we contact EMO for formally making Mikael project lead?

**Comment by mickaelistria** [comment]
> What is the process for retiring an inactive project lead?

As project lead, you're able to retire committers, so you can probably retire Lucas. Then sending an email to EMO should do the trick of officially retiring him.
Don't worry too much about feeling hostile. First, Lucas is a nice and comprehensive guy, then when he concluded his internship, we agreed on the state of Corrosion to progressively remove him, unless he keeps contributing and he agreed with that. So it was anticipated and will feel natural for him to be removed as project lead.

> Do we contact EMO for formally making Mikael project lead?

Maybe, I can't tell. Feel free to ping EMO whenever you want for such stuff ;)

**Comment by Boereck** [comment]
Thanks @mickaelistria! I will retire Lucas then and write EMO about official lead status and ask about the marketplace entry.
