### ISSUE TITLE
Corrosion logo in Eclipse Installer

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#310]
At present the Eclipse Installer uses the standard Eclipse logo for "Eclipse for Rust Development", it should be replaced by the Eclipse Corrosion logo.

**Comment by Boereck** [comment]
This is a configuration in the Oomph project which provides the installer. I already found the spot and will try to contribute the change to Oomph.

**Comment by Boereck** [comment]
Upstream issue is opened [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560616).

**Comment by norru** [comment]
Great, that's my bikeshedding done for today! :D

**Comment by Boereck** [comment]
Well, these tiny things are low hanging fruit and nice fixes, because they can be solved quite fast☺

**Comment by Boereck** [comment]
So, this took a little longer than expected, but the installer is now showing the Corrosion logo.
