### ISSUE TITLE
Implement Outline view

### ISSUE THREAD

**Issue by qseeker** [eclipse/corrosion#32]
Hi
I think that this particular feature is brilliantly done in Eclipse, and I would love to see it realized in Corrosion for Rust in particular.
Here's a screenshot of the outline view displayed by Eclipse for a Java file:
<img src="https://cloud.githubusercontent.com/assets/16356998/16942947/4c382adc-4d99-11e6-8703-a8a64a1ca62d.png">

**Comment by LucasBullen** [comment]
Outline is already implemented in rls and Corrosion:
![screenshot from 2018-02-20 14-11-24](https://user-images.githubusercontent.com/10255066/36444978-c49f36ac-164a-11e8-91fd-32dbcacc49b9.png)
You may have missed it due to an issue found when investigating this issue where the outline will not be shown until the file is edited. Issue reported to rls: https://github.com/rust-lang-nursery/rls/issues/725

**Comment by akurtakov** [comment]
Lucas, can't we simulate edit to force rls to give us the outline? So outline show directly?

**Comment by mickaelistria** [comment]
Note that if the ranges returned by the documentSymbols request in RLS were ranges of the whole node (and not a subset of them), then the outline would be rendered as a tree.
Unfortunately, several LS seem to take a different choice of having the range being for example only the name of the symbol in its declaration (which is a bit weak) and make the Outline less interesting than it could be. See related LSP issues https://github.com/Microsoft/language-server-protocol/issues/327 , https://github.com/Microsoft/language-server-protocol/issues/132#issuecomment-325593176 .

**Comment by LucasBullen** [comment]
Update from rls: When making a request during a build, such as asking for outline on document update or open, the response will be generated from the last completed build, and on new files that means no response will be made.

Either the change will have to be made upstream to allow waiting for builds to complete before getting responses back. Or when we receive the `rustDocument/diagnosticsEnd` message, attempt to refresh the outline view, but I have been unsuccessful in finding a way to refresh outline views.

**Comment by mickaelistria** [comment]
> Either the change will have to be made upstream

Yes, I think that's best. Let's not start wasting resources on workarounds. One of our goals with Corrosion is also to make the RLS better for other IDEs which want to include it, and workarounds in Corrosion are the opposite of that goal.

**Comment by akurtakov** [comment]
Has this been fixed in rls already?

**Comment by LucasBullen** [comment]
No, a contributor said they were going to work on a pr. I asked for an update.

**Comment by mickaelistria** [comment]
I'm closing this one as Corrosion already has an Outline view. Further issues should be tracked in different tickets.
