### ISSUE TITLE
HTML in Content Assist is not rendered

### ISSUE THREAD

**Issue by tweksteen** [eclipse/corrosion#320]
Apologies if the terminology is not exact, I'm not sure how Eclipse names the auto-completion window. A screenshot is easier to understand:

![editor_xml](https://user-images.githubusercontent.com/109376/85134324-996c1280-b23c-11ea-8fd4-049753259f37.png)

In this case the language server (rust-analyzer, #315) provides the definition in Markdown format:
```
[...]
{"additionalTextEdits":[],
 "deprecated":false,
 "detail": "pub fn memchr2(needle1: u8, needle2: u8, haystack: &[u8]) -> Option<usize>",
 "documentation":
  {"kind":"markdown","value":"Like `memchr`, but searches for either of two bytes instead of just one.\n\nThis returns the index corresponding to the first occurrence of `needle1`\nor the first occurrence of `needle2` in `haystack` (whichever occurs\nearlier), or `None` if neither one is found.\n\nWhile this is operationally the same as something like\n`haystack.iter().position(|&b| b == needle1 || b == needle2)`, `memchr2`\nwill use a highly optimized routine that can be up to an order of magnitude\nfaster in some cases.\n\n# Example\n\nThis shows how to find the first position of either of two bytes in a byte\nstring.\n\n```rust\nuse memchr::memchr2;\n\nlet haystack = b\"the quick brown fox\";\nassert_eq!(memchr2(b'k', b'q', haystack), Some(4));\n```"}
``` 

The translation from Markdown to HTML is correctly done by Eclipse (or Corrosion), but it is not rendered.

**Comment by mickaelistria** [comment]
This is generally supposed to work, and working with some other language servers (like the ones in Wild Web Developer).
Is your internal Eclipse browser (used for HTML rendering) properly configured and working? Ie if you open the "Browser" view of the IDE, is it functional?

**Comment by tweksteen** [comment]
No, that's right, my internal web browser was not setup properly. Thanks.
