### ISSUE TITLE
For the love of Dog, please make it stop

### ISSUE THREAD

**Issue by jchimene** [eclipse/corrosion#322]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/4186550/87179227-3d246d80-c293-11ea-99fe-06cadb3c6f5b.png">
}
Yes, I know all about the syntax error.
What's with all the blue lines? Why can't I turn them off?

**Comment by mickaelistria** [comment]
Please read documentation about how to open a good bug report and then create a new ticket.

**Comment by jchimene** [comment]
It was supposed to be a joke.
