### ISSUE TITLE
Downloading rust analyzer gives no progress

### ISSUE THREAD

**Issue by akurtakov** [eclipse/corrosion#359]
After clicking the button and waiting a bit I got the impression nothing happens and had to debug it to find out it's downloading 30+ MB from not so fast location. There has to be some progress so users don't consider it no-op.

**Comment by mickaelistria** [comment]
fixed withhttps://github.com/eclipse/corrosion/pull/363/commits/b269aaa2e64552e73406348545772d326413cba2
