### ISSUE TITLE
Log RLS communications

### ISSUE THREAD

**Issue by LucasBullen** [eclipse/corrosion#36]
To help debug issues, having the communications between the language server and the client recorded and easily accessible would greatly assist in diagnostics and reporting of issues.

**Comment by mickaelistria** [comment]
This should be provided at directly in LSP4E, and LS could simply switch on a setting to enable it. But the general logic would better be shared in LSP4E. Can you please open request to LSP4E?

**Comment by LucasBullen** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532607

**Comment by mickaelistria** [comment]
Thanks a lot!

**Comment by mickaelistria** [comment]
Logging support is shipped in LSP4E 0.6.0, and is included in the Corrosion EPP package.
