### ISSUE TITLE
rust analyzer is downloaded in workspace location

### ISSUE THREAD

**Issue by akurtakov** [eclipse/corrosion#360]
This is quite inconvenient if you have multiple workspace with rust content as one has to setup it multiple times. I know that one can put it on the PATH but this issue is for the purely in IDE experience. To solve similar issue in shellwax I use location in user.home https://github.com/eclipse/shellwax/blob/master/org.eclipse.shellwax.core/src/org/eclipse/shellwax/internal/BashLanguageServer.java#L33 but using Configuration location would already be an improvement as it will allow once download of rust analyzer per eclipse installation.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/corrosion/pull/363/commits/778853a384a9339655aa4537c19358605b0fc55c
