### ISSUE TITLE
Warning about missing RLS in nightly toolchain

### ISSUE THREAD

**Issue by akurtakov** [eclipse/corrosion#361]
After changing toolchain to nightly even with setup rust analyzer as server I get warning about missing rls in the installation.
![Screenshot from 2021-03-11 10-22-11](https://user-images.githubusercontent.com/574788/110757790-75ca7b80-8254-11eb-9099-3fa22b3d3378.png)

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/corrosion/pull/363/commits/598c7b63f45a0f7021b3c0df00efc2830493708b
