### ISSUE TITLE
Do not require rustup if Rust is already installed

### ISSUE THREAD

**Issue by robertvazan** [eclipse/corrosion#367]
It should be possible to use existing installation of Rust, for example by pointing Corrosion to Rust's home directory (parent of its bin directory). Rust installation should not be required to contain `rustup` since installer should not be necessary for existing installation.

At the moment, there is no way to leave Rustup field in configuration empty. Corrosion shows "Rustup and Cargo paths cannot be empty" error and prevents saving the configuration. Specifying dummy path in the Rustup field also results in an error.

**Comment by mickaelistria** [comment]
https://github.com/eclipse/corrosion/commit/85aba35a7896f2640f5bc56e5b42323deb53c568 should have fixed it. Please try latest snapshots from https://download.eclipse.org/corrosion/snapshots/ and reopen if issue is still present.
