### ISSUE TITLE
Create directories before writing to them

### ISSUE THREAD

**Issue by robertvazan** [eclipse/corrosion#368]
I am testing Corrosion in VM now. Operation "Download rust-analyzer" fails with error, because it tries to write into `~/.local/bin`, which does not exist on some computers, including freshly installed VM. This directory must be created if it does not exist yet. The obvious workaround is to create the directory manually before initiating download in Preferences.

**Comment by mickaelistria** [comment]
https://github.com/eclipse/corrosion/commit/421b1bb4171da1a6413040e1e6a065356a515a68 should have fixed it. Please try latest snapshots from https://download.eclipse.org/corrosion/snapshots/ and reopen if issue is still present.
