### ISSUE TITLE
Indexer always out of sync

### ISSUE THREAD

**Issue by Simbi0z** [eclipse/corrosion#375]
Corrosion: Rust edition in Eclipse IDE	1.2.0.202103130942	
 Eclipse IDE for Java Developers	4.19.0.20210311-1200	
Eclipse CDT	Eclipse C/C++ Development Tools	10.2.0.202103011047	

Even tough I fix errors they are not updating in the IDE. This is specially true with source code files with big line count.

**Comment by mickaelistria** [comment]
Please provide more details. What are the minimal steps to reproduce this issue?

**Comment by zwastik** [comment]
It's so general that I though no steps were required. Basically mess with these files until error  message appears (red light bulb), fix it and error will stay no matter what.
[funcs.txt](https://github.com/eclipse/corrosion/files/6593043/funcs.txt)
[main.txt](https://github.com/eclipse/corrosion/files/6593044/main.txt)

**Comment by mickaelistria** [comment]
Please read http://testthewebforward.org/docs/bugs.html and then rework your bug report into something that can be reproduced.

**Comment by zwastik** [comment]
Step 1) I edit line 7 of funcs.rs changing 
`largo: 		u32,`
to
`asdf: 		u32,`

Step 2) Press Ctrl+s to save the file.

[Expected Result]
Red light bulbs signalling errors in the code
[Actual Result]
No changes in the text editor, no messages, no hints.

Step 3) Insert a new line somewhere between two functions.

[Expected Result]
Nothing
[Actual Result]
Hints appear next to line numbers correctly signaling errors that should have appeared in step 2).

Step 4) Restore line 7 to its previous state

Step 5) Press Ctrl+s to save the file.
[Expected Result]
Red light bulbs hints signalling errors in the code disappearing. 
[Actual Result]
Previous hints remain.

Step 6)  Insert a new line somewhere between two functions.

[Expected Result]
Nothing
[Actual Result]
Hints  next to line numbers disappear.

**Comment by akurtakov** [comment]
Do you still face the same issue with latest version?
