### ISSUE TITLE
Line numbers disappeared on updating

### ISSUE THREAD

**Issue by cplir-c** [eclipse/corrosion#377]
My line numbers disappeared when I updated from the January 2021 release of corrosion to the June 2021 release using the Check For Updates button.
I've tried changing my theme from dark theme with reduced colors to default dark theme and restarting eclipse, but it did not help. Before I updated the grey line numbers were showing up just fine.
Now there is space for them to show up to the left of the lines, but it is background colored with no line numbers.

**Comment by akurtakov** [comment]
Do you still face the issue with latest version?

**Comment by akurtakov** [comment]
Closing due to lack of interest from reporter to test it. If you still experience the issue with latest version please reopen with details.
