### ISSUE TITLE
Launching a debug session fails.

### ISSUE THREAD

**Issue by hydra** [eclipse/corrosion#379]
When I right click a source file, with `main()` and select `Debug as` -> `Rust Project` it shows the Eclipse Console view and shows that the program is Terminated.

If I then use the Debug view to relaunch the session I get this error:

```
An internal error occurred during: "Launching hello-world (1)". Cannot read the array length because "launchConfigEnv" is null
```

![image](https://user-images.githubusercontent.com/57075/131681672-7c35e1e5-e2a2-46e3-a635-a34b6ff56718.png)

My current workaround is to add a single variable to the launch configuration, and relaunch, as follows:

![eclipse - add environment variable](https://user-images.githubusercontent.com/57075/131681834-61a41ed5-7fd9-4837-86ec-aabd5c67327b.JPG)

And then I when I relaunch it stops at breakpoints, as follows:

![eclipse - debug session](https://user-images.githubusercontent.com/57075/131682026-d653235d-7d05-4fc1-aa25-f1163a136983.JPG)

This happened in the latest stable version of Eclipse (2021-06) and also in 2021-09-M3A.

Stable:
```
  Corrosion: Rust edition in Eclipse IDE	1.2.1.202106081156	org.eclipse.corrosion.feature.feature.group	Eclipse Corrosion
  Eclipse IDE for C/C++ Developers	4.20.0.20210612-1200	epp.package.cpp	Eclipse Packaging Project
```

Latest:
```
Corrosion: Rust edition in Eclipse IDE	1.2.1.202106081156	org.eclipse.corrosion.feature.feature.group	Eclipse Corrosion
Eclipse IDE for Embedded C/C++ Developers	4.21.0.20210827-1400	epp.package.embedcpp	Eclipse Packaging Project
```

**Comment by mickaelistria** [comment]
Thanks for the details report. It should be relatively easy to fix. Do you feel like you could submit a PR that fixes that, are you familiar with Eclipse plugin development?

**Comment by mickaelistria** [comment]
A fix has been implemented and is now available in https://download.eclipse.org/corrosion/snapshots/ . Please try it and reopen if the issue still occurs.

**Comment by hydra** [comment]
> 
> 
> Thanks for the details report. It should be relatively easy to fix. Do you feel like you could submit a PR that fixes that, are you familiar with Eclipse plugin development?

Hiya, I'm not at all familiar with Eclipse plugin development.  I don't currently have time to fix the issues I raise here myself as I have other commitments in other projects.  Just reporting so that other users that have the same issue arrive here and so that it can be fixed.

I see you have made a new snapshot release, I'll give that a go ASAP and report back if there's still an issue.  Thanks!

**Comment by hydra** [comment]
Confirmed fixed in the version I installed today:

```
Corrosion: Rust edition in Eclipse IDE	1.2.4.202206282034	org.eclipse.corrosion.feature.feature.group	Eclipse Corrosion
```

**Comment by mickaelistria** [comment]
Thanks for the confirmation!
