### ISSUE TITLE
Use HTTPS for download.eclipse.org URLs

### ISSUE THREAD

**Issue by Marcono1234** [eclipse/corrosion#382]
This project contains a few `download.eclipse.org` URLs using `http://` instead of `https://` in Markdown files but also in the `pom.xml`.
The target site supports HTTPS. Could the URLs therefore please be updated to use `https://`?

**Comment by mickaelistria** [comment]
Are you willing to submit a PR about it?

**Comment by Marcono1234** [comment]
Sorry I am not going to create a pull request for this. But this issue covers only `http://download.eclipse.org`, so searching for occurrences of it and replacing them would solve this issue.
