### ISSUE TITLE
Outline error: waiting for cargo metadata or cargo check

### ISSUE THREAD

**Issue by git2013vb** [eclipse/corrosion#394]
Hi,
I use Eclipse 
```
Version: 2021-12 (4.22.0)
Build id: 20211202-1639
```
and 

`  Corrosion: Rust edition in Eclipse IDE	1.2.2.202110280920	org.eclipse.corrosion.feature.feature.group	Eclipse Corrosion`

Any hint about the error in subject?

Thanks :)
Edit:  it show up if I start to edit the file. if I close the file an reopen it the error show again.

**Comment by akurtakov** [comment]
We released version 1.2.3 on January 26th https://github.com/eclipse/corrosion/releases/tag/1.2.3 . Do you still face the issue with it?

**Comment by git2013vb** [comment]
Thank you for the answer :)

I tried the the eclipse as suggested in main page https://download.eclipse.org/corrosion/releases/latest/products/

(Eclipse.org	Eclipse Platform	4.22.0.v20211124-1800	org.eclipse.platform). That is from November instead December ;) 

But its fine for now. It work. 

When I will have a bit of time Ill try to use the later version of Eclipse (December)

Thanks.

**Comment by hydra** [comment]
Same issue with latest version of Eclipse and Corrosion, details and solution here:

https://github.com/rust-lang/rust-analyzer/issues/10910#issuecomment-1225823218

**Comment by hydra** [comment]
This issue is still not resolved, I tried again today with latest rust-analyzer and snapshot version of corrosion, details on this comment: https://github.com/rust-lang/rust-analyzer/issues/10910#issuecomment-1422332052
