### ISSUE TITLE
Continuous Build and download area

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#40]
To be sustainable and welcoming of new contributors, Corrosion should set up a CI system and also make the snapshots of latest build constantly available for testing.
I suggest Corrosion can mimic how aCute is setup: https://ci.eclipse.org/acute/ It uses the Jenkins pipeline plugin and Jenkinsfile and so far, it works great.

**Comment by akurtakov** [comment]
Mickael, can you point to the bz for having acute JIPP setup so Lucas can replicate?

**Comment by mickaelistria** [comment]
I think for aCute it got provisionned automatically because I asked it from project creation. But I think it's simply a matter of asking at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community&component=CI-Jenkins , and while doing it, you need also to ask for installation of the pipeline plugin and GitHub plugin if they're not already in.

**Comment by LucasBullen** [comment]
@mickaelistria Do you mean https://plugins.jenkins.io/github-branch-source when you say the GitHub plugins and what is the pipeline plugin?

**Comment by mickaelistria** [comment]
I don't know which one it is, I just asked webmaster and it worked. But it'\s very likely this one.
Also, I believe support for pipeline/Jenkinsfile is included in Jenkins out of the box, so a plugin for it may not be necessary.

**Comment by LucasBullen** [comment]
Jenkins set up at https://ci.eclipse.org/corrosion/, updates to master are reflected on the p2 download site
