### ISSUE TITLE
Rust -> Debug preferences shows error message in macOS and prevents debugging

### ISSUE THREAD

**Issue by apetrelli** [eclipse/corrosion#403]
Hello
I am using macOS Monterey and Eclipse Corrosion as a plugin.
Installed rustup and rust-analyzer from the buttons.
I am not able to debug, since, when I go to the Rust -> Debug preferences page I see error messages.
For the default rust-dbg I see:
Error with command: rust-gdb --version [cause: Cannot run program "rust-gdb": Unknown reason]
When I put the complete path:
/Users/antonio_petrelli/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rust-gdb
I see this message:
Could not determine GDB version using command: /Users/antonio_petrelli/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rust-gdb --version [cause: /Users/antonio_petrelli/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rust-gdb: line 21: exec: gdb: not found]

Notice that, when I run rust-gdb version from command line, it works. I installed gdb via homebrew.

**Comment by akurtakov** [comment]
There are no active developers using MacOS so you'll have to investigate the issue on your own. Please make sure that you use latest build when testing.

**Comment by apetrelli** [comment]
@akurtakov me neither, I have not a Macbook anymore (luckily, I'm back to Linux), so... who cares :-D

**Comment by akurtakov** [comment]
Well, closing in this case :) If/when a Mac developer is ready to help he/she can freely reopen.
