### ISSUE TITLE
Adding Corrosion to an exiting Eclipse installation apparently does nothing

### ISSUE THREAD

**Issue by aberent** [eclipse/corrosion#408]
I installed a new Eclipse installation (Eclipse IDE for C/C++ developers) and added Corrosion from the Marketplace. On restarting Eclipse I see no Rust features.

In particular, the new project dialog doesn't allow me to create Rust projects, and Rust syntax highlighting doesn't work.

Downloading the Eclipse Corrosion IDE from https://download.eclipse.org/corrosion/releases/latest/products/ appears to work correctly

Version details:

Version: 2022-06 (4.24.0)
Build id: 20220609-1112

OS: Ubuntu 22.04 LTS

Installation details:

  C/C++ Autotools support	10.7.0.202205060838	org.eclipse.cdt.autotools.feature.group	Eclipse CDT
  C/C++ CMake Build Support - Preview	10.7.0.202206081803	org.eclipse.cdt.cmake.feature.group	Eclipse CDT
  C/C++ Development Tools	10.7.0.202206081808	org.eclipse.cdt.feature.group	Eclipse CDT
  C/C++ Docker Container Launch Support	10.7.0.202205210108	org.eclipse.cdt.docker.launcher.feature.group	Eclipse CDT
  C/C++ GCC Cross Compiler Support	10.7.0.202204200013	org.eclipse.cdt.build.crossgcc.feature.group	Eclipse CDT
  C/C++ GDB Hardware Debugging	10.7.0.202204241640	org.eclipse.cdt.debug.gdbjtag.feature.group	Eclipse CDT
  C/C++ Launch over Serial	10.7.0.202204200013	org.eclipse.cdt.launch.serial.feature.feature.group	Eclipse CDT
  C/C++ Library API Documentation Hover Help	8.7.0.202206072042	org.eclipse.linuxtools.cdt.libhover.feature.feature.group	Eclipse Linux Tools
  C/C++ Memory View Enhancements	10.7.0.202204200013	org.eclipse.cdt.debug.ui.memory.feature.group	Eclipse CDT
  C/C++ Meson Build Support - Preview	10.7.0.202204200013	org.eclipse.cdt.meson.feature.group	Eclipse CDT
  C/C++ Remote Launch	10.7.0.202205060838	org.eclipse.cdt.launch.remote.feature.group	Eclipse CDT
  C/C++ Standalone Debugger	10.7.0.202204200013	org.eclipse.cdt.debug.standalone.feature.group	Eclipse CDT
  C/C++ Unit Testing Support	10.7.0.202204200013	org.eclipse.cdt.testsrunner.feature.feature.group	Eclipse CDT
  ChangeLog Management Tools for C/C++	8.7.0.202206072042	org.eclipse.linuxtools.changelog.c.feature.group	Eclipse Linux Tools
  Corrosion: Rust edition in Eclipse IDE	1.2.4.202206282034	org.eclipse.corrosion.feature.feature.group	Eclipse Corrosion
  Eclipse IDE for C/C++ Developers	4.24.0.20220609-1200	epp.package.cpp	Eclipse Packaging Project
  Eclipse Platform	4.24.0.v20220607-0700	org.eclipse.platform.feature.group	Eclipse.org
  Eclipse RCP	4.24.0.v20220607-0700	org.eclipse.rcp.feature.group	Eclipse.org
  GCov Integration	8.7.0.202206072042	org.eclipse.linuxtools.gcov.feature.group	Eclipse Linux Tools
  GDB Tracepoint Analysis	8.0.0.202206082347	org.eclipse.tracecompass.gdbtrace.feature.group	Eclipse Trace Compass
  Git integration for Eclipse	6.2.0.202206071550-r	org.eclipse.egit.feature.group	Eclipse EGit
  GProf Integration	8.7.0.202206072042	org.eclipse.linuxtools.gprof.feature.feature.group	Eclipse Linux Tools
  Java implementation of Git	6.2.0.202206071550-r	org.eclipse.jgit.feature.group	Eclipse JGit
  LaunchBar	10.7.0.202204200013	org.eclipse.launchbar.feature.group	Eclipse CDT
  Library Hover help for devhelp documentation	8.7.0.202206072042	org.eclipse.linuxtools.cdt.libhover.devhelp.feature.feature.group	Eclipse Linux Tools
  LTTng Kernel Analysis	8.0.0.202206082347	org.eclipse.tracecompass.lttng2.kernel.feature.group	Eclipse Trace Compass
  LTTng Tracer Control	8.0.0.202206082347	org.eclipse.tracecompass.lttng2.control.feature.group	Eclipse Trace Compass
  LTTng Userspace Analysis	8.0.0.202206082347	org.eclipse.tracecompass.lttng2.ust.feature.group	Eclipse Trace Compass
  Marketplace Client	1.10.0.v20220502-0731	org.eclipse.epp.mpc.feature.group	Eclipse Marketplace Client
  Mylyn WikiText	3.0.42.202201072301	org.eclipse.mylyn.wikitext_feature.feature.group	Eclipse Mylyn
  Oomph Setup	1.25.0.v20220607-1104	org.eclipse.oomph.setup.feature.group	Eclipse Oomph Project
  Remote Launch Targets	10.7.0.202204200013	org.eclipse.launchbar.remote.feature.group	Eclipse CDT
  RPM Tools	8.7.0.202206072042	org.eclipse.linuxtools.rpm.feature.group	Eclipse Linux Tools
  TM Terminal	10.7.0.202204110055	org.eclipse.tm.terminal.feature.feature.group	Eclipse CDT
  TM Terminal Serial Connector Extensions	10.7.0.202204200013	org.eclipse.tm.terminal.connector.cdtserial.feature.feature.group	Eclipse CDT
  Valgrind Tools Integration	8.7.0.202206072042	org.eclipse.linuxtools.valgrind.feature.group	Eclipse Linux Tools

**Comment by mickaelistria** [comment]
> In particular, the new project dialog doesn't allow me to create Rust projects, and Rust syntax highlighting doesn't work.

Can you please check the <workspace>/.metadata/.log file?

**Comment by aberent** [comment]
Explained by looking at the .log file. My default version of Java was Java 11 whereas Corrosion appears to require Java 17. No idea, however, why this isn't a problem with the Rust IDE.

Since the Eclipse documentation says that Eclipse only requires Java 11 this should, at least, be documented.

The log file is attached in case you need more information. The error is at line 1664.
[Eclipse-log.txt](https://github.com/eclipse/corrosion/files/9056491/Eclipse-log.txt)
.

**Comment by akurtakov** [comment]
When you download Rust IDE it comes with its own Java 17 version which is used. I have updated the Marketplace entry to state it requires Java 17 thus I consider this one done.
