### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by rhfkrhfk** [eclipse/corrosion#409]
Error when installing sts3 in Eclipse Market
![캡처](https://user-images.githubusercontent.com/109146513/178473263-4ab60902-e837-4300-9de8-0e045b24cca2.PNG)

I need a hand.

**Comment by akurtakov** [comment]
How does this relates to Corrosion? If it relates what are the exact steps to reproduce?

**Comment by akurtakov** [comment]
Still I don't see any relation with Eclipse Corrosion (aka Eclipse Rust IDE) . Have you installed https://download.eclipse.org/corrosion/releases/1.2.4/products/ ?

**Comment by rhfkrhfk** [comment]
> 여전히 Eclipse Corrosion(Eclipse Rust IDE라고도 함)과 관련이 없습니다. https://download.eclipse.org/corrosion/releases/1.2.4/products/ 를 설치 하셨습니까?

No, where should I put it?
