### ISSUE TITLE
The p2 site does not work for installing the plugin

### ISSUE THREAD

**Issue by koutheir** [eclipse/corrosion#41]
The p2 site (https://lucasbullen.github.io/corrosion/site/) does not work for installing the plugin, as documented in `documentation/Installation.md`.

**Comment by mickaelistria** [comment]
URL is now https://eclipse.github.io/corrosion/site/ . Can you please submit a pull request with this change?

**Comment by LucasBullen** [comment]
No, the p2 site is currently being hosted outside the repo at https://s3.ca-central-1.amazonaws.com/eclipseredox/ since the move to Eclipse and until issue #40 is resolved. Will update documentation to reflect.

**Comment by mickaelistria** [comment]
@LucasBullen I have some credentials to directly push content to download.eclipse.org via scp. Would you like me to make a local build and push results to http://download.eclipse.org/corrosion/snapshots so the URL is already there and can be referenced in documentation?

**Comment by LucasBullen** [comment]
@mickaelistria Yes, that would be great.

**Comment by mickaelistria** [comment]
repo published at http://download.eclipse.org/corrosion/snapshots/ (using build update from #43)

**Comment by LucasBullen** [comment]
@koutheir do you wish to resubmit your patch?

**Comment by koutheir** [comment]
This would be unnecessary if the issue #46 is resolved.

**Comment by LucasBullen** [comment]
Commit e88525f fixed the docs to point to the correct p2 site. Thanks @koutheir for the help.
