### ISSUE TITLE
Standalone download doesn't work on macOS Monterey

### ISSUE THREAD

**Issue by domino2** [eclipse/corrosion#411]
Hello, I just wanted to install standalone version on 
macOS Monterey 12.5.1
2.3 GHz 8-Core Intel Core i9

downloaded from https://download.eclipse.org/corrosion/releases/
I tried versions
1.2.3 and 1.2.4 of
 eclipseide-rust-1.2.4-macosx.cocoa.x86_64.tar.gz
 
 and I have got an error saying 
'“Eclipse” is damaged and can’t be opened.'

I'm not an admin of this device, but this shouldn't be a problem in this case.

**Comment by mickaelistria** [comment]
Thanks for the report. At the moment, none of the active maintainers of Corrosion do have a mac as far as I know.
Would you be willing to investigate further and provide details about what Corrosion can do to not appear as damaged?

**Comment by domino2** [comment]
I will, I tried to build from source and got couple issues. I can't go over the current one, so I'm looking for a solution.
It is different issue, so I don't want to deal with it under this ticket.

**Comment by mickaelistria** [comment]
> so I don't want to deal with it under this ticket.

OK, feel free to open as many issues you think are necessary.

**Comment by domino2** [comment]
Hi, just wanted to return after couple busy days.
So, I'm able to do own Eclipse and Corrosion plugin builds and also I'm ready to do Rust as I've been able to run "hello word" without an issue.

Because I have older Java in my system, I thought that this issue may be related.

I used same command to run downloaded Eclipse.app Corrosion version and got an error message as mentioned above.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/605
But I'm able to run my own build.

**Comment by akurtakov** [comment]
> Hi, just wanted to return after couple busy days. So, I'm able to do own Eclipse and Corrosion plugin builds and also I'm ready to do Rust as I've been able to run "hello word" without an issue.

Thanks for getting back to us that things are working now!

**Comment by domino2** [comment]
@akurtakov I think it doesn't work still.
I went to [https://download.eclipse.org/corrosion/releases/latest/products/](https://download.eclipse.org/corrosion/releases/latest/products/ )
downloaded **eclipseide-rust-1.2.4-macosx.cocoa.x86_64.tar.gz** and I'm still getting an error message saying that the app is damaged.

**Comment by akurtakov** [comment]
I don't think new release is out. Would you please try with the latest snapshot from https://download.eclipse.org/corrosion/snapshots/products/ ? If it works we will release.

**Comment by domino2** [comment]
It doesn't ... just to be complete.
I'm able to run my own build by openjdk 11 and 17
`open -a "$(pwd)/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/target/products/org.eclipse.platform.ide/macosx/cocoa/x86_64/Eclipse.app" --args -vm /usr/local/Cellar/openjdk@11/11.0.16.1_1/bin`

`open -a "$(pwd)/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/target/products/org.eclipse.platform.ide/macosx/cocoa/x86_64/Eclipse.app" --args -vm /usr/local/Cellar/openjdk@17/17.0.4.1_1/bin`

But downloaded file not:
`open -a "$(pwd)/Eclipse.app" --args -vm /usr/local/Cellar/openjdk@11/11.0.16.1_1/bin`

`open -a "$(pwd)/Eclipse.app" --args -vm /usr/local/Cellar/openjdk@17/17.0.4.1_1/bin`

Both commands giving me same error as I mentioned on top.

I've requested admin access, so I tried to run it with sudo and got this:
> The application /Users/.../Downloads/Eclipse.app cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600002a4d080 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

Nothing useful I would to say.

This may be (not) useful, but double click gives me same error, so not the message about the wrong java version as my system's default is 8. I'm getting this message when running my build with the java 8.
