### ISSUE TITLE
Do not include dependencies in feature.xml

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#45]
When built, the feature.xml files locks to a specific version of each dependency. In most cases, this is not desired as it can make updates of other extensions failing. For example, the dependency on mylyn.wilkitext on the feature here could prevent from updating mylyn because Corrosion locks it to a specific version on the feature.
The rule is generally to "include only what you build" in the feature.
Other dependencies can be added as extra to the p2 repo so they can be resolved at best during installation. See for example how aCute does that: 
* feature with only "owned" content: https://github.com/eclipse/aCute/blob/master/org.eclipse.acute.feature/feature.xml
* repo containing extra stuff for depdendency resolution https://github.com/eclipse/aCute/blob/master/repository/category.xml

This will quickly become a blocker for people who want to try Corrosion, or even if we want to make progress with integration in SimRel and packaging as an EPP product.

**Comment by LucasBullen** [comment]
Fixed with d49ffd0
