### ISSUE TITLE
Generate a local update site or archive

### ISSUE THREAD

**Issue by koutheir** [eclipse/corrosion#46]
To ease testing of Corrosion without having to run multiple Eclipse instances, is there a way to generate a local update site or an archive that can be provided to Eclipse in order to install a locally built version of Corrosion?

**Comment by mickaelistria** [comment]
Yes, you can do `mvn clean verify` from the repo root, and then the p2 repository that you can use to test the built artifact can be found in `repository/target/repository`.

**Comment by koutheir** [comment]
There is no directory called `repository/target/repository` in the repository root. The issue is still open.

**Comment by mickaelistria** [comment]
Did you run the `mvn clean verify` from current HEAD commit of master?

**Comment by koutheir** [comment]
Yes, and the build/test succeeded.

**Comment by LucasBullen** [comment]
@koutheir, can you try again with the latest master? Then post the results of the `mvn clean install` result, the `corrosion` root directory contents, the `corrosion/repository` contents, and hopefully the `corrosion/repository/target` contents. In the latter there should be a `repository` folder. Then we will use that as your local p2 site. If not hopefully the results/screenshots will shine some more light on the situation.

**Comment by koutheir** [comment]
Just tried it again today, and this time it works. I have no idea what was wrong, but something went wrong on two different computers. Well, at least right now it works. Thank you.
