### ISSUE TITLE
Content Assist stops working

### ISSUE THREAD

**Issue by davidbalme** [eclipse/corrosion#57]
Today I installed corrosion plugin  via the eclipse market place.

When I first open up eclipse with a trivial rust project, content assist appears to work..
ie I have the following ..

let mut x: Vec<u32> = Vec::new();

then
x. <ctl-space>  gives me a list of vector functions.. ( tho' not all of them .. I never see iter() for example)

then when I use this feature a couple of times the list goes away

.. restart eclipse and it seems to work again.

Is there a way for me to debug this?

My environment
---
Eclipse corrosion plugin:    Corrosion: Rust edition in Eclipse IDE	0.1.0.201804131828	org.eclipse.corrosion.feature.feature.group	Red Hat Inc.
Platform :  ubuntu 14.4
eclipse oxygen Apr-2018
rustc --version
rustc 1.25.0 (84203cac6 2018-03-25)

rust language server appears to be running ..
ps -ef | grep rls
david    22008 21937  0 21:52 ?        00:00:03 /home/david/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rls

**Comment by mickaelistria** [comment]
You should be able to log the messages between the IDE and the language server: Window > Preferences > Language Servers has some options about logging. Try to enable logging for RLS and then reproduce your problem, then share the log file for analysis
Thanks in advance!

**Comment by davidbalme** [comment]
Thank you for the quick response ..

I can't see how to enable RLS logging via eclipse ..

Here is the option you mention

![image](https://user-images.githubusercontent.com/5666876/39473424-d4d3f3ba-4d1c-11e8-8043-dc12b0460941.png)

Top portion of the above configuration dialog seems to be fixed ( not editable)
Bottom portion; I tried to re-associate RLS to rust files..  but that did not work.. probably because it is already associated in the "static" config?  I'm guessing here ..   I'm sure it's just a case of : I don't know what I am doing! :-)

Anyhow, as an FYI; I was mistaken in my previous post.  Content assist is never working in my environment even when it appears to be.  :-) .. When I do get a list of functions from content assist the list appears to be incorrect because it list functions that are not part of the vector trait.   Perhaps its something wrong with the rust language server itself that I am running.  If you have any tips on how to debug that it would be great..   I'm hunting and pecking to see if I can at least turn on logging on the rls server side..  so far I haven't found anything yet..

Being a spoiled java developer, I find I cannot live without content assist.  I don't know how developers who just use vi/vim can do it..  :-)

**Comment by mickaelistria** [comment]
> I can't see how to enable RLS logging via eclipse ..

Ok, I see from your screenshot that an older version of LSP4E is installed. I'll see if I can provide an updated version or recommend another approach for you to use latest version of this important dependencies, which brings logging.

>  Perhaps its something wrong with the rust language server itself that I am running. If you have any tips on how to debug that it would be great.

There is a dependency on former point.

> Being a spoiled java developer, I find I cannot live without content assist. I don't know how developers who just use vi/vim can do it.. :-)

You don't have to convince us. All contributors to this project are Java developers and Eclipse IDE users, we're on the same page ;)
Not that VIM has extensions to enable Language Servers too, with completion and so on, and has some ways to render errors, content-assist, hover doc... I hope developers that just use vim are aware of those and do take advantage of them.

**Comment by mickaelistria** [comment]
Most of the effort for Corrosion is currently targeting next version of Eclipse IDE.
Can you please give a try to one of the Rust packages available at https://ci.eclipse.org/packaging/job/photon.epp-tycho-build/lastSuccessfulBuild/artifact/org.eclipse.epp.packages/archive/ and see whether things get better?

**Comment by davidbalme** [comment]
ok will do -- currently I use the latest version of Oxygen.

**Comment by LucasBullen** [comment]
@davidbalme are you still experiencing this issue?

**Comment by jcbritobr** [comment]
Im, and im using the latest eclipse photon.

**Comment by LucasBullen** [comment]
@jcbritobr would you be able to share your LSP4E logs? Confirm that `org.eclipse.corrosion.RLS` logs are being recorded in your preference (Language Servers > Logs). The `org.eclipse.corrosion.rls.log` file is in your workspace under a directory called `languageServers-log`.

If you know what steps cause the content assist to stop, you can turn on console logging and just share the console output

**Comment by davidbalme** [comment]
Apologies just noticed this question now.

I no longer use eclipse for rust work ..  Using vscode for the moment.
However I would like to go back to eclipse - as am more used to it and more
productive with it.  Old dawg, new tricks and all that jazz.

**Comment by madmajestro** [comment]
Im using the latest eclipse version and tried corrosion for the first time.
There are no useful completion proposals at all.

Actually i do my first steps learning rust and i simply tried to copy and paste the "hello world" project of the tokio.rs homepage. If i delete any ".unwrap();" at the line-endings i get only proposals like "for", "unimplemented", "unreachable"... but nothing useful.

Here is my logfile:

[org.eclipse.corrosion.rls.log](https://github.com/eclipse/corrosion/files/2320234/org.eclipse.corrosion.rls.log)

**Comment by mickaelistria** [comment]
@madmajestro your issue seems very different from the initial report. Please open a separate ticket for it.

**Comment by qseeker** [comment]
@mickaelistria I'll do it. Got the same.

**Comment by madmajestro** [comment]
@qseeker I openend #117 for our problem a few days ago

**Comment by mickaelistria** [comment]
Can you please retry it with the "Eclipse IDE for Rust Developers" package you can find on https://www.eclipse.org/downloads/index-developer.php ?

**Comment by mickaelistria** [comment]
No feedback after my last question 1+ month ago. I'm closing the issue. Feel free to reopen if it still happens.

**Comment by clandestinenetworks** [comment]
yeah still not working
