### ISSUE TITLE
Project not showing up when created outside of workspace

### ISSUE THREAD

**Issue by dc740** [eclipse/corrosion#63]
The project contents are not shown. You only see the project name/folder, and you can't expand it right after you create it. I also tried creating the project manually. It still doesn't work.
I had to manually switch to the Rust perspective, but the project explorer still shows an empty project.

I tried a brand new installation getting an Eclipse package, and through the Eclipse installer too.  Both times I went to the marketplace, installed Corrosion, restarted Eclipse, and created a new project. The bug is still present.

Config:
LUbuntu 18.04LTS x64
OpenJDK 10.0.1 2018-04-17

**Comment by mickaelistria** [comment]
Also, could you please try to pick the best rust package for your environment at https://ci.eclipse.org/packaging/job/photon.epp-tycho-build/lastSuccessfulBuild/artifact/org.eclipse.epp.packages/archive/ and give it a try and report whether it makes a difference?

**Comment by dc740** [comment]
Hi, thanks for the reply. I found the root cause!

1) I created it through the Eclipse UI. File -> New -> Other -> Rust -> Cargo project. The project folder is OUTSIDE of the workspace. IT WORKS WHEN I CREATE THE PROJECT INSIDE THE WORKSPACE (something I never do for any project I've worked with, and in my particular case, it's a requirement)
2) Yes, Cargo.toml and src/main.rs (I'm using the binary template during the project creation)
3) Yes, I confirm the project is open. The one I created inside the workspace is showing up just fine, and the one I created outside is not showing anything. It looks empty
4) The log does not say anything related to this. It only complains that one of my keybindings didn't work.
`!ENTRY org.eclipse.ui 2 0 2018-05-14 09:39:32.425
!MESSAGE Warnings while parsing the images from the 'org.eclipse.ui.commandImages' extension point.
!SUBENTRY 1 org.eclipse.ui 2 0 2018-05-14 09:39:32.425
!MESSAGE Cannot bind to an undefined command: plug-in='org.eclipse.lsp4e', id='org.eclipse.lsp4e.togglehighlight'

!ENTRY org.eclipse.jface 2 0 2018-05-14 09:39:33.820
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2018-05-14 09:39:33.820
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5c8d631,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3d42b756,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)`

**Comment by mickaelistria** [comment]
Thanks for the details. It helps a lot and I hope I'll be able to provide a fix soon.

**Comment by mickaelistria** [comment]
commit https://github.com/eclipse/corrosion/commit/9a28742b899c112d4d167aed5ba9b94f1d5e26e7 should fix it.
A build is already available with this patch included. You can try it at http://download.eclipse.org/corrosion/snapshots . Please give it a try and feel free to reopen if this doesn't work.

**Comment by dc740** [comment]
Thank you! It works. I also tested removing the project and re-importing it, and it also worked OK.
