### ISSUE TITLE
Can't launch rust project

### ISSUE THREAD

**Issue by akurtakov** [eclipse/corrosion#74]
Trying to launch rust project ends up in "Unable to find project". Reverting to two days old commit makes it work again.

**Comment by akurtakov** [comment]
CargoRunDelegate.java#106 String projectName = configuration.getAttribute(PROJECT_ATTRIBUTE, ""); //$NON-NLS-1$ doesn't return the projectName for some reason.

**Comment by LucasBullen** [comment]
Fixed with 9b68b11

**Comment by akurtakov** [comment]
Shouldn't there be a test case verifying it ?

**Comment by mickaelistria** [comment]
+100 for a test case if we can have one.

**Comment by LucasBullen** [comment]
There was a test case but it was built incorrectly. @mickaelistria can you help me with an issue? Looking at my newest commit (2e1232c) I have fixed the test case to use the CargoRunDelegate logic to launch the run configuration to better test the process.

However, when there is an issue, such as removing the fix I added in my previous commit, a popup dialog appears informing the user no project is found, but this stops the DisplayHelper from continuing its waitForCondition countdown leaving the test to hang. Any suggestions for how to capture the creation of the popup so it can be dismissed? this is the same issue causing me to disable failing run configuration tests.

**Comment by mickaelistria** [comment]
You may be able to check for popup in DisplayHelper condition. Something like

```java
new DisplayHelper() {
  public boolean test() {
    return psitiveResult() || errorPopup();
  }
}.waitForCondition(1000);
assertTrue(positiveResult);
assertFalse(errorPopup);
```
with
```java
public boolean errorPopup() {
  for (Shell shell : getDisplay().getShell()) {
    if (shell.getText().equals("my error message")) {
      return true;
  }
}
```

Is this the kind of hint you're looking for?

**Comment by mickaelistria** [comment]
If you don't need the result of the Dialog, in your code, you can try
```java
Dialog dialog = new MessageDialog(...);
dialog.setBlockOnOpen(false);
dialog.open();
```
instead of `MessageDialog.openError(...)`.

Another possibility (didn't try) is to add a listener on the Display to find if shell was open
```java
Display.getDefault().addListener(SWT.Activate, e -> if (e.widget instanceof Shell && e.widget.getText().equals("error title"))) fail("error shell poped up");
```

Those are just speculations, I actually didn't try any of them ;)
