### ISSUE TITLE
"rustup" and "cargo" not be found at their default locations on Windows

### ISSUE THREAD

**Issue by howlger** [eclipse/corrosion#86]
On windows **_rustup_** and **_cargo_** are **not found** at their default locations. The following screenshot shows the preference dialog _Windows > Preferences: Rust_ after starting the _Eclipse IDE for Rust Developers_ for the first time:

![rust_pref_before](https://user-images.githubusercontent.com/5197918/41645526-8aef5e48-7471-11e8-9533-9aeeb57cacda.png)

As a workaround, the checkbox can be deactivated, the paths for _rustup_ and _cargo_ entered manually and the _Toolchain_ can be switched to e. g. _Stable_ (screenshot for Windows user `User`):

![rust_pref_after](https://user-images.githubusercontent.com/5197918/41645541-97bdc56a-7471-11e8-947a-3185430085b8.png)

**Comment by anb0s** [comment]
I've also tried to solve this issue with putting ".cargo\bin" folder to PATH env., but it does not find rustup and cargo executables.

**Comment by mickaelistria** [comment]
I believe none of current contributors do use Windows. So if anyone facing this issue could submit a working patch for Windows, that would be helpful!

**Comment by anb0s** [comment]
Is there some info about "How To" build and contribute to this project?

**Comment by anb0s** [comment]
sorry, i've found it now: https://github.com/eclipse/corrosion/blob/master/documentation/Installation.md#using-github

**Comment by mihaiandrei1294** [comment]
Hello. I also have this problem, but worse. "rustup" and "cargo" cannot be found and I *can't* enter them manually. I mean, I can uncheck "Use default paths" and enter them manually, but when I prass "Apply" then "Apply and Close" they are not saved. When I open again the preferences, "Use default paths" is still checked and there are no paths.

Thus, I can't use eclipse for Rust at all.

**Comment by howlger** [comment]
@mihaiandrei1294 Does it work if you replace the backslashes `\` with normal slashes `/` before you press _Apply_?

**Comment by LucasBullen** [comment]
Tested @howlger's patch on windows and it worked for me. If anyone still has issues on windows then please reopen this issue.
