### ISSUE TITLE
Set program command line when debugging

### ISSUE THREAD

**Issue by koutheir** [eclipse/corrosion#90]
Is there a way to set the command line provided to the program while debugging?

I can set the debugger options and the environment variables, but not the command line. Without this, developing command line programs is not an option.

**Comment by LucasBullen** [comment]
Good find. Looking into it now and current investigation shows that the console streams are getting mixed up with the CDT's gdb streams to the program. Running a simple program that prints the user input sometimes returns what seems to be the gdb commands (ex `27-list-thread-groups`, `26-gdb-exit`) 

If you give input in the console, then terminate the connection through the Debug view (not the Console Terminate button) then the program returns what was written.

Will continue with investigation.

**Comment by norru** [comment]
@koutheir if it helps, the Rust Debug configuration has been recently added an "Arguments" tab which you can use to build your command line in most cases (can combine this with the Executable) field in the "main" tab.

![selection_098](https://user-images.githubusercontent.com/889291/48475571-07489080-e7f5-11e8-9872-b0d787ba1ff2.png)

You may need to upgrade Corrosion to latest via the Corrosion Snapshot update site (which might be unstable at times).

**Comment by mickaelistria** [comment]
@koutheir Did you try it? Is it a good solution for your case? Can we close this issue?

**Comment by koutheir** [comment]
I am not still using this software, so I have no idea if this fix works.

**Comment by mickaelistria** [comment]
Ok, so let's just say it works until someone says otherwise.
