### ISSUE TITLE
Is it possible to import an existing Cargo project in Corrosion ?

### ISSUE THREAD

**Issue by Riduidel** [eclipse/corrosion#92]
I have a simple Rust project I've started before, and I want to use it in Corrosion.

I tried to use the classical "File / Import" menu, but there is no Cargo wizard.

Then I tried to create a new Cargo project in the folder where my Cargo file already exists, but it doesn't seems to be possible to use an existing Cargo file (unless I create the project from Git, in which case I should delete my local folder to have it re-created the wizard).

Am I doing something wrong ?

Or is it a missing feature a contributor could try to implement ?

**Comment by mickaelistria** [comment]
Have you tried File > Import Projects from Filesystem... ?

**Comment by LucasBullen** [comment]
Currently the only restriction on a project being considered a Rust project is the existence of a `Cargo.toml` file within the project. If you use the File > Import Projects tool from Filesystem and import your project from there, then it will work as expected.

If there should be different logic for validating if a project is a Rust project then please say so and we are open to pull requests. The logic change would be made in [CargoProjectTester.java](https://github.com/eclipse/corrosion/blob/master/org.eclipse.corrosion/src/org/eclipse/corrosion/cargo/core/CargoProjectTester.java)

**Comment by Riduidel** [comment]
The solution provided by @mickaelistria worked correctly. Thank you !
However, @LucasBullen , the File > Import Projects Window doesn't see my folder as a Rust project although there is a cargo.toml file.

Project can be seen at https://github.com/Riduidel/codingame/tree/master/multiplayer/code_of_kutulu and was checked out (with the containing project) on a Windows machine (may be signifiant regarding to case)

**Comment by LucasBullen** [comment]
That is because there is no concept of a Rust project in Eclipse's perspective so we import projects as normal projects and only validate if it is a Rust project when we try and run it. Glad it is working for you now!

**Comment by Riduidel** [comment]
You closed it (and you're fundamentally right to do so, after all it's your project, not mine). However, I have the weird feeling there *should* be a Cargo import item in the import menu, just to have interface coherent. What do you think about that point ? (I'm not willing here to put you in a bad position, I just want to be sure)

**Comment by mickaelistria** [comment]
I don't think it's worth multiplying UI entries and if there is no added-value in specific import wizards, we shouldn't add some.
It's mostly a matter of getting users used to trying first `File > Import projects from Filesystem...`.

**Comment by LucasBullen** [comment]
We ran into this issue [before](https://github.com/eclipse/corrosion/commit/c0a057b6d942a4e11e140acb41a529f278136b17) and the result was that an importer at this time wouldn't do anything different than the standard importer.

The rebuttal is if this is the second issue being opened looking for a rust project importer, then there is a case that we should make one for UX reasons even if it will do nothing. @mickaelistria thoughts?

**Comment by mickaelistria** [comment]
> @mickaelistria thoughts?

Part of UX is also to educate users to better workflows, and multiplying UI entries is also about keeping users confused.
But, for this, I would make just a wizard that is empty, not Finishable and just contain a message "Use File > Import Projects from Filesystem..." to import Cargo projects; with no link; just to force users to educate themselves in doing the right moves.

**Comment by Riduidel** [comment]
Couldn't it possible to have that wizard use the "import project from 
filesystem ..." ?

As a Eclipse user, I don't know why there is a difference between those 
two wizards (and frankly, I've always used import project for my maven 
projects (which are not present in import from filesystem), so it's more 
a question of being used to one UI path ...


Le 28/06/2018 à 16:06, Mickael Istria a écrit :

**Comment by mickaelistria** [comment]
> Couldn't it possible to have that wizard use the "import project from
> filesystem ..." ?
>

I don't think another entry-point for the same wizard is a good thing.
Redirecting users to do the best thing seems better.


> As a Eclipse user, I don't know why there is a difference between those
> two wizards (and frankly, I've always used import project for my maven
> projects (which are not present in import from filesystem), so it's more
> a question of being used to one UI path ...


Importing Maven projects from "Import Projects from Filesystem..." should
work, and is one good entry-point. If it doesn't please report bugs to m2e
(and put me as CC ;) )

**Comment by HighCommander4** [comment]
In case anyone cares, I too was looking for an `Import -> Existing Cargo project` option or similar, and was about to file an issue about it when I found this one.
